import { sqliteTable, text, integer, real, index, uniqueIndex } from "drizzle-orm/sqlite-core";
import { game } from "./games";

export const ftn_charting = sqliteTable(
  "ftn_charting",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    gameId: integer("game_id").references(() => game.id),
    ftnGameId: integer("ftn_game_id"),
    season: real("season"),
    week: real("week"),
    ftnPlayId: text("ftn_play_id").notNull(),
    nflversePlayId: text("nflverse_play_id").notNull(),
    startingHash: text("starting_hash"),
    qbLocation: text("qb_location"),
    nOffenseBackfield: integer("n_offense_backfield"),
    nDefenseBox: integer("n_defense_box"),
    isNoHuddle: integer("is_no_huddle", { mode: "boolean" }).notNull(),
    isMotion: integer("is_motion", { mode: "boolean" }).notNull(),
    isPlayAction: integer("is_play_action", { mode: "boolean" }).notNull(),
    isScreenPass: integer("is_screen_pass", { mode: "boolean" }).notNull(),
    isRpo: integer("is_rpo", { mode: "boolean" }).notNull(),
    isTrickPlay: integer("is_trick_play", { mode: "boolean" }).notNull(),
    isQbOutOfPocket: integer("is_qb_out_of_pocket", { mode: "boolean" }).notNull(),
    isInterceptionWorthy: integer("is_interception_worthy", { mode: "boolean" }).notNull(),
    isThrowAway: integer("is_throw_away", { mode: "boolean" }).notNull(),
    readThrown: text("read_thrown"),
    isCatchableBall: integer("is_catchable_ball", { mode: "boolean" }).notNull(),
    isContestedBall: integer("is_contested_ball", { mode: "boolean" }).notNull(),
    isCreatedReception: integer("is_created_reception", { mode: "boolean" }).notNull(),
    isDrop: integer("is_drop", { mode: "boolean" }).notNull(),
    isQbSneak: integer("is_qb_sneak", { mode: "boolean" }).notNull(),
    nBlitzers: integer("n_blitzers"),
    nPassRushers: integer("n_pass_rushers"),
    isQbFaultSack: integer("is_qb_fault_sack", { mode: "boolean" }).notNull(),
    datePulled: integer("date_pulled", { mode: "timestamp_ms" }),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("ftn_game_idx").on(t.gameId),
    uniqueIndex("ftn_play_idx").on(t.nflversePlayId),
  ],
);
