import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";
import { player, team } from "./reference";

export const draft_pick = sqliteTable(
  "draft_pick",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    season: integer("season"),
    round: integer("round"),
    pick: integer("pick"),
    hof: integer("hof", { mode: "boolean" }).notNull(),
    position: text("position"),
    category: text("category"),
    side: text("side"),
    college: text("college"),
    age: integer("age"),
    to: integer("to"),
    allpro: integer("allpro"),
    probowls: integer("probowls"),
    seasonsStarted: integer("seasons_started"),
    wAv: integer("w_av"),
    carAv: text("car_av").notNull(),
    drAv: integer("dr_av"),
    games: integer("games"),
    passCompletions: integer("pass_completions"),
    passAttempts: integer("pass_attempts"),
    passYards: integer("pass_yards"),
    passTds: integer("pass_tds"),
    passInts: integer("pass_ints"),
    rushAtts: integer("rush_atts"),
    rushYards: integer("rush_yards"),
    rushTds: integer("rush_tds"),
    receptions: integer("receptions"),
    recYards: integer("rec_yards"),
    recTds: integer("rec_tds"),
    defSoloTackles: integer("def_solo_tackles"),
    defInts: integer("def_ints"),
    defSacks: real("def_sacks"),
  },
  (t) => [
    index("draft_season_idx").on(t.season),
    index("draft_player_idx").on(t.playerId),
  ],
);

export const combine_result = sqliteTable(
  "combine_result",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    season: integer("season"),
    draftYear: real("draft_year"),
    draftTeam: text("draft_team"),
    draftRound: real("draft_round"),
    draftOvr: real("draft_ovr"),
    playerName: text("player_name"),
    pos: text("pos"),
    school: text("school"),
    ht: text("ht"),
    wt: real("wt"),
    forty: real("forty"),
    bench: real("bench"),
    vertical: real("vertical"),
    broadJump: real("broad_jump"),
    cone: real("cone"),
    shuttle: real("shuttle"),
  },
  (t) => [
    index("combine_season_idx").on(t.season),
  ],
);
