import { sqliteTable, text, integer, real, index, uniqueIndex } from "drizzle-orm/sqlite-core";
import { official, team, player } from "./reference";

export const game_official = sqliteTable(
  "game_official",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    gameId: integer("game_id").notNull().references(() => game.id),
    officialId: integer("official_id").notNull().references(() => official.id),
    position: text("position"),
    jerseyNumber: text("jersey_number"),
    season: integer("season"),
    seasonType: text("season_type").notNull(),
    week: integer("week"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    uniqueIndex("game_official_idx").on(t.gameId, t.officialId),
    index("game_official_official_idx").on(t.officialId),
  ],
);

export const game = sqliteTable(
  "game",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    awayTeamId: integer("away_team_id").references(() => team.id),
    homeTeamId: integer("home_team_id").references(() => team.id),
    weather: text("weather"),
    awayQbId: integer("away_qb_id").references(() => player.id),
    homeQbId: integer("home_qb_id").references(() => player.id),
    slug: text("slug").notNull(),
    season: integer("season"),
    gameType: text("game_type").notNull(),
    week: integer("week"),
    gameday: integer("gameday", { mode: "timestamp_ms" }),
    weekday: text("weekday").notNull(),
    gametime: text("gametime"),
    awayScore: integer("away_score"),
    homeScore: integer("home_score"),
    location: text("location").notNull(),
    result: integer("result"),
    total: integer("total"),
    overtime: integer("overtime", { mode: "boolean" }),
    awayRest: integer("away_rest"),
    homeRest: integer("home_rest"),
    awayMoneyline: integer("away_moneyline"),
    homeMoneyline: integer("home_moneyline"),
    spreadLine: real("spread_line"),
    awaySpreadOdds: integer("away_spread_odds"),
    homeSpreadOdds: integer("home_spread_odds"),
    totalLine: real("total_line"),
    underOdds: integer("under_odds"),
    overOdds: integer("over_odds"),
    divGame: integer("div_game", { mode: "boolean" }).notNull(),
    roof: text("roof"),
    surface: text("surface"),
    temp: real("temp"),
    wind: real("wind"),
    homeQbName: text("home_qb_name"),
    awayQbName: text("away_qb_name"),
    awayCoach: text("away_coach"),
    homeCoach: text("home_coach"),
    referee: text("referee"),
    stadiumId: text("stadium_id"),
    stadium: text("stadium"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    uniqueIndex("game_slug_idx").on(t.slug),
    index("game_week_idx").on(t.season, t.week),
    index("game_home_idx").on(t.homeTeamId),
    index("game_away_idx").on(t.awayTeamId),
  ],
);
