import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";
import { player, team } from "./reference";

export const pfr_adv_def_season = sqliteTable(
  "pfr_adv_def_season",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    season: integer("season"),
    age: real("age"),
    g: real("g"),
    gs: real("gs"),
    pos: text("pos"),
    int: real("int"),
    tgt: real("tgt"),
    cmp: real("cmp"),
    cmpPercent: real("cmp_percent"),
    yds: real("yds"),
    ydsCmp: real("yds_cmp"),
    ydsTgt: real("yds_tgt"),
    td: real("td"),
    rat: real("rat"),
    dadot: real("dadot"),
    air: real("air"),
    yac: real("yac"),
    bltz: real("bltz"),
    hrry: real("hrry"),
    qbkd: real("qbkd"),
    sk: real("sk"),
    prss: real("prss"),
    comb: real("comb"),
    mTkl: real("m_tkl"),
    mTklPercent: real("m_tkl_percent"),
    bats: real("bats"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_def_szn_player_idx").on(t.playerId),
  ],
);

export const pfr_adv_pass_season = sqliteTable(
  "pfr_adv_pass_season",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    season: integer("season"),
    passAttempts: real("pass_attempts"),
    throwaways: real("throwaways"),
    spikes: real("spikes"),
    drops: real("drops"),
    dropPct: real("drop_pct"),
    badThrows: real("bad_throws"),
    badThrowPct: real("bad_throw_pct"),
    pocketTime: real("pocket_time"),
    timesBlitzed: real("times_blitzed"),
    timesHurried: real("times_hurried"),
    timesHit: real("times_hit"),
    timesPressured: real("times_pressured"),
    pressurePct: real("pressure_pct"),
    battedBalls: real("batted_balls"),
    onTgtThrows: real("on_tgt_throws"),
    onTgtPct: real("on_tgt_pct"),
    rpoPlays: real("rpo_plays"),
    rpoYards: real("rpo_yards"),
    rpoPassAtt: real("rpo_pass_att"),
    rpoPassYards: real("rpo_pass_yards"),
    rpoRushAtt: real("rpo_rush_att"),
    rpoRushYards: real("rpo_rush_yards"),
    paPassAtt: real("pa_pass_att"),
    paPassYards: real("pa_pass_yards"),
    intendedAirYards: real("intended_air_yards"),
    intendedAirYardsPerPassAttempt: real("intended_air_yards_per_pass_attempt"),
    completedAirYards: real("completed_air_yards"),
    completedAirYardsPerCompletion: real("completed_air_yards_per_completion"),
    completedAirYardsPerPassAttempt: real("completed_air_yards_per_pass_attempt"),
    passYardsAfterCatch: real("pass_yards_after_catch"),
    passYardsAfterCatchPerCompletion: real("pass_yards_after_catch_per_completion"),
    scrambles: real("scrambles"),
    scrambleYardsPerAttempt: real("scramble_yards_per_attempt"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_pass_szn_player_idx").on(t.playerId),
  ],
);

export const pfr_adv_rush_season = sqliteTable(
  "pfr_adv_rush_season",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    season: integer("season"),
    age: real("age"),
    g: real("g"),
    gs: real("gs"),
    pos: text("pos"),
    att: real("att"),
    yds: real("yds"),
    td: real("td"),
    x1d: real("x1d"),
    ybc: real("ybc"),
    ybcAtt: real("ybc_att"),
    yac: real("yac"),
    yacAtt: real("yac_att"),
    brkTkl: real("brk_tkl"),
    attBr: real("att_br"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_rush_szn_player_idx").on(t.playerId),
  ],
);

export const pfr_adv_rec_season = sqliteTable(
  "pfr_adv_rec_season",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    season: integer("season"),
    age: real("age"),
    g: real("g"),
    gs: real("gs"),
    pos: text("pos"),
    tgt: real("tgt"),
    rec: real("rec"),
    yds: real("yds"),
    td: real("td"),
    x1d: real("x1d"),
    ybc: real("ybc"),
    ybcR: real("ybc_r"),
    yac: real("yac"),
    yacR: real("yac_r"),
    adot: real("adot"),
    brkTkl: real("brk_tkl"),
    recBr: real("rec_br"),
    drop: real("drop"),
    dropPercent: real("drop_percent"),
    int: real("int"),
    rat: real("rat"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_rec_szn_player_idx").on(t.playerId),
  ],
);

export const pfr_adv_def_week = sqliteTable(
  "pfr_adv_def_week",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    pfrGameId: text("pfr_game_id"),
    season: integer("season"),
    week: integer("week"),
    gameType: text("game_type").notNull(),
    opponent: text("opponent"),
    pfrPlayerName: text("pfr_player_name"),
    pfrPlayerId: text("pfr_player_id"),
    defInts: real("def_ints"),
    defTargets: real("def_targets"),
    defCompletionsAllowed: real("def_completions_allowed"),
    defCompletionPct: real("def_completion_pct"),
    defYardsAllowed: real("def_yards_allowed"),
    defYardsAllowedPerCmp: real("def_yards_allowed_per_cmp"),
    defYardsAllowedPerTgt: real("def_yards_allowed_per_tgt"),
    defReceivingTdAllowed: real("def_receiving_td_allowed"),
    defPasserRatingAllowed: real("def_passer_rating_allowed"),
    defAdot: real("def_adot"),
    defAirYardsCompleted: real("def_air_yards_completed"),
    defYardsAfterCatch: real("def_yards_after_catch"),
    defTimesBlitzed: real("def_times_blitzed"),
    defTimesHurried: real("def_times_hurried"),
    defTimesHitqb: real("def_times_hitqb"),
    defSacks: real("def_sacks"),
    defPressures: real("def_pressures"),
    defTacklesCombined: real("def_tackles_combined"),
    defMissedTackles: real("def_missed_tackles"),
    defMissedTacklePct: real("def_missed_tackle_pct"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_def_wk_player_idx").on(t.playerId),
  ],
);

export const pfr_adv_pass_week = sqliteTable(
  "pfr_adv_pass_week",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    pfrGameId: text("pfr_game_id"),
    season: integer("season"),
    week: integer("week"),
    gameType: text("game_type").notNull(),
    opponent: text("opponent"),
    pfrPlayerName: text("pfr_player_name"),
    pfrPlayerId: text("pfr_player_id"),
    passingDrops: real("passing_drops"),
    passingDropPct: real("passing_drop_pct"),
    receivingDrop: real("receiving_drop"),
    receivingDropPct: real("receiving_drop_pct"),
    passingBadThrows: real("passing_bad_throws"),
    passingBadThrowPct: real("passing_bad_throw_pct"),
    timesSacked: real("times_sacked"),
    timesBlitzed: real("times_blitzed"),
    timesHurried: real("times_hurried"),
    timesHit: real("times_hit"),
    timesPressured: real("times_pressured"),
    timesPressuredPct: real("times_pressured_pct"),
    defTimesBlitzed: real("def_times_blitzed"),
    defTimesHurried: real("def_times_hurried"),
    defTimesHitqb: real("def_times_hitqb"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_pass_wk_player_idx").on(t.playerId),
  ],
);

export const pfr_adv_rec_week = sqliteTable(
  "pfr_adv_rec_week",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    pfrGameId: text("pfr_game_id"),
    season: integer("season"),
    week: integer("week"),
    gameType: text("game_type").notNull(),
    opponent: text("opponent"),
    pfrPlayerName: text("pfr_player_name"),
    pfrPlayerId: text("pfr_player_id"),
    passingDrops: real("passing_drops"),
    passingDropPct: real("passing_drop_pct"),
    receivingDrop: real("receiving_drop"),
    receivingDropPct: real("receiving_drop_pct"),
    rushingBrokenTackles: real("rushing_broken_tackles"),
    receivingBrokenTackles: real("receiving_broken_tackles"),
    receivingInt: real("receiving_int"),
    receivingRat: real("receiving_rat"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_rec_wk_player_idx").on(t.playerId),
  ],
);

export const pfr_adv_rush_week = sqliteTable(
  "pfr_adv_rush_week",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    pfrGameId: text("pfr_game_id"),
    season: integer("season"),
    week: integer("week"),
    gameType: text("game_type").notNull(),
    opponent: text("opponent"),
    pfrPlayerName: text("pfr_player_name"),
    pfrPlayerId: text("pfr_player_id"),
    carries: real("carries"),
    rushingYardsBeforeContact: real("rushing_yards_before_contact"),
    rushingYardsBeforeContactAvg: real("rushing_yards_before_contact_avg"),
    rushingYardsAfterContact: real("rushing_yards_after_contact"),
    rushingYardsAfterContactAvg: real("rushing_yards_after_contact_avg"),
    rushingBrokenTackles: real("rushing_broken_tackles"),
    receivingBrokenTackles: real("receiving_broken_tackles"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("pfr_adv_rush_wk_player_idx").on(t.playerId),
  ],
);
