import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";
import { game } from "./games";
import { team, player } from "./reference";

export const play = sqliteTable(
  "play",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    gameId: integer("game_id").references(() => game.id),
    posteamId: integer("posteam_id").references(() => team.id),
    defteamId: integer("defteam_id").references(() => team.id),
    playId: text("play_id").notNull(),
    week: integer("week"),
    posteamType: text("posteam_type"),
    yardline100: real("yardline_100"),
    quarterSecondsRemaining: real("quarter_seconds_remaining"),
    halfSecondsRemaining: real("half_seconds_remaining"),
    gameSecondsRemaining: real("game_seconds_remaining"),
    gameHalf: text("game_half").notNull(),
    quarterEnd: integer("quarter_end", { mode: "boolean" }).notNull(),
    drive: real("drive"),
    sp: integer("sp", { mode: "boolean" }).notNull(),
    qtr: real("qtr"),
    down: real("down"),
    goalToGo: real("goal_to_go"),
    time: text("time"),
    yrdln: text("yrdln"),
    ydstogo: real("ydstogo"),
    ydsnet: real("ydsnet"),
    desc: text("desc"),
    playType: text("play_type"),
    yardsGained: real("yards_gained"),
    shotgun: integer("shotgun", { mode: "boolean" }).notNull(),
    noHuddle: integer("no_huddle", { mode: "boolean" }).notNull(),
    qbDropback: integer("qb_dropback", { mode: "boolean" }),
    qbKneel: integer("qb_kneel", { mode: "boolean" }),
    qbSpike: integer("qb_spike", { mode: "boolean" }),
    qbScramble: integer("qb_scramble", { mode: "boolean" }),
    passLength: text("pass_length"),
    passLocation: text("pass_location"),
    airYards: real("air_yards"),
    yardsAfterCatch: real("yards_after_catch"),
    runLocation: text("run_location"),
    runGap: text("run_gap"),
    fieldGoalResult: text("field_goal_result"),
    kickDistance: real("kick_distance"),
    extraPointResult: text("extra_point_result"),
    twoPointConvResult: text("two_point_conv_result"),
    homeTimeoutsRemaining: real("home_timeouts_remaining"),
    awayTimeoutsRemaining: real("away_timeouts_remaining"),
    timeout: integer("timeout", { mode: "boolean" }),
    totalHomeScore: real("total_home_score"),
    totalAwayScore: real("total_away_score"),
    posteamScore: real("posteam_score"),
    defteamScore: real("defteam_score"),
    scoreDifferential: real("score_differential"),
    posteamScorePost: real("posteam_score_post"),
    defteamScorePost: real("defteam_score_post"),
    scoreDifferentialPost: real("score_differential_post"),
    noScoreProb: real("no_score_prob"),
    oppFgProb: real("opp_fg_prob"),
    oppSafetyProb: real("opp_safety_prob"),
    oppTdProb: real("opp_td_prob"),
    fgProb: real("fg_prob"),
    safetyProb: real("safety_prob"),
    tdProb: real("td_prob"),
    extraPointProb: real("extra_point_prob"),
    twoPointConversionProb: real("two_point_conversion_prob"),
    ep: real("ep"),
    epa: real("epa"),
    totalHomeEpa: real("total_home_epa"),
    totalAwayEpa: real("total_away_epa"),
    totalHomeRushEpa: real("total_home_rush_epa"),
    totalAwayRushEpa: real("total_away_rush_epa"),
    totalHomePassEpa: real("total_home_pass_epa"),
    totalAwayPassEpa: real("total_away_pass_epa"),
    airEpa: real("air_epa"),
    yacEpa: real("yac_epa"),
    compAirEpa: real("comp_air_epa"),
    compYacEpa: real("comp_yac_epa"),
    totalHomeCompAirEpa: real("total_home_comp_air_epa"),
    totalAwayCompAirEpa: real("total_away_comp_air_epa"),
    totalHomeCompYacEpa: real("total_home_comp_yac_epa"),
    totalAwayCompYacEpa: real("total_away_comp_yac_epa"),
    totalHomeRawAirEpa: real("total_home_raw_air_epa"),
    totalAwayRawAirEpa: real("total_away_raw_air_epa"),
    totalHomeRawYacEpa: real("total_home_raw_yac_epa"),
    totalAwayRawYacEpa: real("total_away_raw_yac_epa"),
    wp: real("wp"),
    defWp: real("def_wp"),
    homeWp: real("home_wp"),
    awayWp: real("away_wp"),
    wpa: real("wpa"),
    vegasWpa: real("vegas_wpa"),
    vegasHomeWpa: real("vegas_home_wpa"),
    homeWpPost: real("home_wp_post"),
    awayWpPost: real("away_wp_post"),
    vegasWp: real("vegas_wp"),
    vegasHomeWp: real("vegas_home_wp"),
    totalHomeRushWpa: real("total_home_rush_wpa"),
    totalAwayRushWpa: real("total_away_rush_wpa"),
    totalHomePassWpa: real("total_home_pass_wpa"),
    totalAwayPassWpa: real("total_away_pass_wpa"),
    airWpa: real("air_wpa"),
    yacWpa: real("yac_wpa"),
    compAirWpa: real("comp_air_wpa"),
    compYacWpa: real("comp_yac_wpa"),
    totalHomeCompAirWpa: real("total_home_comp_air_wpa"),
    totalAwayCompAirWpa: real("total_away_comp_air_wpa"),
    totalHomeCompYacWpa: real("total_home_comp_yac_wpa"),
    totalAwayCompYacWpa: real("total_away_comp_yac_wpa"),
    totalHomeRawAirWpa: real("total_home_raw_air_wpa"),
    totalAwayRawAirWpa: real("total_away_raw_air_wpa"),
    totalHomeRawYacWpa: real("total_home_raw_yac_wpa"),
    totalAwayRawYacWpa: real("total_away_raw_yac_wpa"),
    puntBlocked: integer("punt_blocked", { mode: "boolean" }),
    firstDownRush: integer("first_down_rush", { mode: "boolean" }),
    firstDownPass: integer("first_down_pass", { mode: "boolean" }),
    firstDownPenalty: integer("first_down_penalty", { mode: "boolean" }),
    thirdDownConverted: integer("third_down_converted", { mode: "boolean" }),
    thirdDownFailed: integer("third_down_failed", { mode: "boolean" }),
    fourthDownConverted: integer("fourth_down_converted", { mode: "boolean" }),
    fourthDownFailed: integer("fourth_down_failed", { mode: "boolean" }),
    incompletePass: integer("incomplete_pass", { mode: "boolean" }),
    touchback: integer("touchback", { mode: "boolean" }),
    interception: integer("interception", { mode: "boolean" }),
    puntInsideTwenty: integer("punt_inside_twenty", { mode: "boolean" }),
    puntInEndzone: integer("punt_in_endzone", { mode: "boolean" }),
    puntOutOfBounds: integer("punt_out_of_bounds", { mode: "boolean" }),
    puntDowned: integer("punt_downed", { mode: "boolean" }),
    puntFairCatch: integer("punt_fair_catch", { mode: "boolean" }),
    kickoffInsideTwenty: integer("kickoff_inside_twenty", { mode: "boolean" }),
    kickoffInEndzone: integer("kickoff_in_endzone", { mode: "boolean" }),
    kickoffOutOfBounds: integer("kickoff_out_of_bounds", { mode: "boolean" }),
    kickoffDowned: integer("kickoff_downed", { mode: "boolean" }),
    kickoffFairCatch: integer("kickoff_fair_catch", { mode: "boolean" }),
    fumbleForced: integer("fumble_forced", { mode: "boolean" }),
    fumbleNotForced: integer("fumble_not_forced", { mode: "boolean" }),
    fumbleOutOfBounds: integer("fumble_out_of_bounds", { mode: "boolean" }),
    soloTackle: integer("solo_tackle", { mode: "boolean" }),
    safety: integer("safety", { mode: "boolean" }),
    penalty: integer("penalty", { mode: "boolean" }),
    tackledForLoss: integer("tackled_for_loss", { mode: "boolean" }),
    fumbleLost: integer("fumble_lost", { mode: "boolean" }),
    ownKickoffRecovery: integer("own_kickoff_recovery", { mode: "boolean" }),
    ownKickoffRecoveryTd: integer("own_kickoff_recovery_td", { mode: "boolean" }),
    qbHit: integer("qb_hit", { mode: "boolean" }),
    rushAttempt: integer("rush_attempt", { mode: "boolean" }),
    passAttempt: integer("pass_attempt", { mode: "boolean" }),
    sack: integer("sack", { mode: "boolean" }),
    touchdown: integer("touchdown", { mode: "boolean" }),
    passTouchdown: integer("pass_touchdown", { mode: "boolean" }),
    rushTouchdown: integer("rush_touchdown", { mode: "boolean" }),
    returnTouchdown: integer("return_touchdown", { mode: "boolean" }),
    extraPointAttempt: integer("extra_point_attempt", { mode: "boolean" }),
    twoPointAttempt: integer("two_point_attempt", { mode: "boolean" }),
    fieldGoalAttempt: integer("field_goal_attempt", { mode: "boolean" }),
    kickoffAttempt: integer("kickoff_attempt", { mode: "boolean" }),
    puntAttempt: integer("punt_attempt", { mode: "boolean" }),
    fumble: integer("fumble", { mode: "boolean" }),
    completePass: integer("complete_pass", { mode: "boolean" }),
    assistTackle: integer("assist_tackle", { mode: "boolean" }),
    lateralReception: integer("lateral_reception", { mode: "boolean" }),
    lateralRush: integer("lateral_rush", { mode: "boolean" }),
    lateralReturn: integer("lateral_return", { mode: "boolean" }),
    lateralRecovery: integer("lateral_recovery", { mode: "boolean" }),
    passingYards: real("passing_yards"),
    receivingYards: real("receiving_yards"),
    rushingYards: real("rushing_yards"),
    lateralReceivingYards: real("lateral_receiving_yards"),
    lateralRushingYards: real("lateral_rushing_yards"),
    tackleWithAssist: integer("tackle_with_assist", { mode: "boolean" }),
    fumbleRecovery1Yards: real("fumble_recovery_1_yards"),
    fumbleRecovery2Yards: real("fumble_recovery_2_yards"),
    returnYards: real("return_yards"),
    penaltyYards: real("penalty_yards"),
    replayOrChallenge: integer("replay_or_challenge", { mode: "boolean" }),
    replayOrChallengeResult: text("replay_or_challenge_result"),
    penaltyType: text("penalty_type"),
    defensiveTwoPointAttempt: integer("defensive_two_point_attempt", { mode: "boolean" }),
    defensiveTwoPointConv: integer("defensive_two_point_conv", { mode: "boolean" }),
    defensiveExtraPointAttempt: integer("defensive_extra_point_attempt", { mode: "boolean" }),
    defensiveExtraPointConv: integer("defensive_extra_point_conv", { mode: "boolean" }),
    season: integer("season"),
    cp: real("cp"),
    cpoe: real("cpoe"),
    series: real("series"),
    seriesSuccess: integer("series_success", { mode: "boolean" }).notNull(),
    seriesResult: text("series_result"),
    orderSequence: real("order_sequence"),
    playClock: text("play_clock"),
    playDeleted: integer("play_deleted", { mode: "boolean" }),
    playTypeNfl: text("play_type_nfl"),
    specialTeamsPlay: integer("special_teams_play", { mode: "boolean" }),
    stPlayType: text("st_play_type"),
    endClockTime: text("end_clock_time"),
    endYardLine: text("end_yard_line"),
    fixedDrive: real("fixed_drive"),
    fixedDriveResult: text("fixed_drive_result").notNull(),
    driveRealStartTime: text("drive_real_start_time").notNull(),
    drivePlayCount: real("drive_play_count"),
    driveTimeOfPossession: text("drive_time_of_possession"),
    driveFirstDowns: real("drive_first_downs"),
    driveInside20: integer("drive_inside20", { mode: "boolean" }),
    driveEndedWithScore: integer("drive_ended_with_score", { mode: "boolean" }),
    driveQuarterStart: real("drive_quarter_start"),
    driveQuarterEnd: real("drive_quarter_end"),
    driveYardsPenalized: real("drive_yards_penalized"),
    driveStartTransition: text("drive_start_transition"),
    driveEndTransition: text("drive_end_transition"),
    driveGameClockStart: text("drive_game_clock_start"),
    driveGameClockEnd: text("drive_game_clock_end"),
    driveStartYardLine: text("drive_start_yard_line"),
    driveEndYardLine: text("drive_end_yard_line"),
    drivePlayIdStarted: text("drive_play_id_started").notNull(),
    drivePlayIdEnded: text("drive_play_id_ended").notNull(),
    abortedPlay: integer("aborted_play", { mode: "boolean" }).notNull(),
    success: integer("success", { mode: "boolean" }),
    pass: integer("pass", { mode: "boolean" }).notNull(),
    rush: integer("rush", { mode: "boolean" }).notNull(),
    firstDown: integer("first_down", { mode: "boolean" }),
    special: integer("special", { mode: "boolean" }).notNull(),
    play: integer("play", { mode: "boolean" }).notNull(),
    outOfBounds: integer("out_of_bounds", { mode: "boolean" }).notNull(),
    homeOpeningKickoff: integer("home_opening_kickoff", { mode: "boolean" }).notNull(),
    qbEpa: real("qb_epa"),
    xyacEpa: real("xyac_epa"),
    xyacMeanYardage: real("xyac_mean_yardage"),
    xyacMedianYardage: real("xyac_median_yardage"),
    xyacSuccess: real("xyac_success"),
    xyacFd: real("xyac_fd"),
    xpass: real("xpass"),
    passOe: real("pass_oe"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("play_game_idx").on(t.gameId),
    index("play_season_week_idx").on(t.season, t.week),
    index("play_posteam_idx").on(t.posteamId),
  ],
);

export const play_player = sqliteTable(
  "play_player",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playId: integer("play_id").notNull().references(() => play.id),
    role: text("role").notNull(),
    slot: integer("slot"),
    playerId: integer("player_id").references(() => player.id),
    playerName: text("player_name"),
    teamId: integer("team_id").references(() => team.id),
    jerseyNumber: text("jersey_number"),
  },
  (t) => [
    index("play_player_play_idx").on(t.playId),
    index("play_player_player_idx").on(t.playerId),
    index("play_player_role_idx").on(t.role),
  ],
);

export const play_team = sqliteTable(
  "play_team",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playId: integer("play_id").notNull().references(() => play.id),
    role: text("role").notNull(),
    teamId: integer("team_id").references(() => team.id),
    rawValue: text("raw_value"),
  },
  (t) => [
    index("play_team_play_idx").on(t.playId),
    index("play_team_team_idx").on(t.teamId),
    index("play_team_role_idx").on(t.role),
  ],
);
