import { sqliteTable, text, integer, real, index, uniqueIndex } from "drizzle-orm/sqlite-core";
import { player, team } from "./reference";
import { game } from "./games";

export const player_week_stats = sqliteTable(
  "player_week_stats",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").notNull().references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    opponentTeamId: integer("opponent_team_id").references(() => team.id),
    gameId: integer("game_id").references(() => game.id),
    position: text("position"),
    positionGroup: text("position_group"),
    headshotUrl: text("headshot_url"),
    season: integer("season"),
    seasonType: text("season_type").notNull(),
    completions: integer("completions"),
    attempts: integer("attempts"),
    passingYards: real("passing_yards"),
    passingTds: integer("passing_tds"),
    passingInterceptions: integer("passing_interceptions"),
    sacksSuffered: integer("sacks_suffered"),
    sackYardsLost: real("sack_yards_lost"),
    sackFumbles: integer("sack_fumbles"),
    sackFumblesLost: integer("sack_fumbles_lost"),
    passingAirYards: real("passing_air_yards"),
    passingYardsAfterCatch: real("passing_yards_after_catch"),
    passingFirstDowns: integer("passing_first_downs"),
    passingEpa: real("passing_epa"),
    passingCpoe: real("passing_cpoe"),
    passing2ptConversions: integer("passing_2pt_conversions"),
    pacr: real("pacr"),
    passing10: integer("passing_10"),
    passing16: integer("passing_16"),
    passing20: integer("passing_20"),
    passing40: integer("passing_40"),
    carries: integer("carries"),
    rushingYards: real("rushing_yards"),
    rushingTds: integer("rushing_tds"),
    rushingFumbles: integer("rushing_fumbles"),
    rushingFumblesLost: integer("rushing_fumbles_lost"),
    rushingFirstDowns: integer("rushing_first_downs"),
    rushingEpa: real("rushing_epa"),
    rushing2ptConversions: integer("rushing_2pt_conversions"),
    rushing10: integer("rushing_10"),
    rushing12: integer("rushing_12"),
    rushing20: integer("rushing_20"),
    rushing40: integer("rushing_40"),
    receptions: integer("receptions"),
    targets: integer("targets"),
    receivingYards: integer("receiving_yards"),
    receivingTds: integer("receiving_tds"),
    receivingFumbles: integer("receiving_fumbles"),
    receivingFumblesLost: integer("receiving_fumbles_lost"),
    receivingAirYards: real("receiving_air_yards"),
    receivingYardsAfterCatch: real("receiving_yards_after_catch"),
    receivingFirstDowns: integer("receiving_first_downs"),
    receivingEpa: real("receiving_epa"),
    receiving2ptConversions: integer("receiving_2pt_conversions"),
    receiving10: integer("receiving_10"),
    receiving16: integer("receiving_16"),
    receiving20: integer("receiving_20"),
    receiving40: integer("receiving_40"),
    racr: real("racr"),
    targetShare: real("target_share"),
    airYardsShare: real("air_yards_share"),
    wopr: real("wopr"),
    specialTeamsTds: integer("special_teams_tds"),
    defTacklesSolo: real("def_tackles_solo"),
    defTacklesWithAssist: real("def_tackles_with_assist"),
    defTackleAssists: real("def_tackle_assists"),
    defTacklesForLoss: real("def_tackles_for_loss"),
    defTacklesForLossYards: real("def_tackles_for_loss_yards"),
    defFumblesForced: integer("def_fumbles_forced"),
    defSacks: real("def_sacks"),
    defSackYards: real("def_sack_yards"),
    defQbHits: real("def_qb_hits"),
    defInterceptions: real("def_interceptions"),
    defInterceptionYards: real("def_interception_yards"),
    defPassDefended: real("def_pass_defended"),
    defTds: real("def_tds"),
    defFumbles: real("def_fumbles"),
    defSafeties: real("def_safeties"),
    defPuntBlocks: real("def_punt_blocks"),
    defPatBlocks: real("def_pat_blocks"),
    defFgBlocks: real("def_fg_blocks"),
    def2ptAtts: real("def_2pt_atts"),
    def2ptMade: real("def_2pt_made"),
    miscYards: real("misc_yards"),
    fumbleRecoveryOwn: real("fumble_recovery_own"),
    fumbleRecoveryYardsOwn: real("fumble_recovery_yards_own"),
    fumbleRecoveryOpp: real("fumble_recovery_opp"),
    fumbleRecoveryYardsOpp: real("fumble_recovery_yards_opp"),
    fumbleRecoveryTds: real("fumble_recovery_tds"),
    penalties: real("penalties"),
    penaltyYards: real("penalty_yards"),
    timeouts: real("timeouts"),
    fumblesForcedByOpp: real("fumbles_forced_by_opp"),
    fumblesNotForced: real("fumbles_not_forced"),
    fumblesOutOfBounds: real("fumbles_out_of_bounds"),
    fumblesTotal: real("fumbles_total"),
    fumblesLostTotal: real("fumbles_lost_total"),
    puntReturns: real("punt_returns"),
    puntReturnYards: real("punt_return_yards"),
    kickoffReturns: real("kickoff_returns"),
    kickoffReturnYards: real("kickoff_return_yards"),
    fgMade: real("fg_made"),
    fgAtt: real("fg_att"),
    fgMissed: real("fg_missed"),
    fgBlocked: real("fg_blocked"),
    fgLong: real("fg_long"),
    fgPct: real("fg_pct"),
    fgMade019: real("fg_made_0_19"),
    fgMade2029: real("fg_made_20_29"),
    fgMade3039: real("fg_made_30_39"),
    fgMade4049: real("fg_made_40_49"),
    fgMade5059: real("fg_made_50_59"),
    fgMade60_: real("fg_made_60_"),
    fgMissed019: real("fg_missed_0_19"),
    fgMissed2029: real("fg_missed_20_29"),
    fgMissed3039: real("fg_missed_30_39"),
    fgMissed4049: real("fg_missed_40_49"),
    fgMissed5059: real("fg_missed_50_59"),
    fgMissed60_: real("fg_missed_60_"),
    fgMadeList: text("fg_made_list", { mode: "json" }).$type<number[]>().notNull(),
    fgMissedList: text("fg_missed_list", { mode: "json" }).$type<number[]>().notNull(),
    fgBlockedList: text("fg_blocked_list", { mode: "json" }).$type<number[]>().notNull(),
    fgMadeDistance: real("fg_made_distance"),
    fgMissedDistance: real("fg_missed_distance"),
    fgBlockedDistance: real("fg_blocked_distance"),
    patMade: real("pat_made"),
    patAtt: real("pat_att"),
    patMissed: real("pat_missed"),
    patBlocked: real("pat_blocked"),
    patPct: real("pat_pct"),
    gwfgMade: real("gwfg_made"),
    gwfgAtt: real("gwfg_att"),
    gwfgMissed: real("gwfg_missed"),
    gwfgBlocked: real("gwfg_blocked"),
    ptAtt: real("pt_att"),
    ptBlocked: real("pt_blocked"),
    ptLong: real("pt_long"),
    ptYards: real("pt_yards"),
    ptInside20: real("pt_inside_20"),
    ptOutOfBounds: real("pt_out_of_bounds"),
    ptDowned: real("pt_downed"),
    ptTouchback: real("pt_touchback"),
    ptFairCaught: real("pt_fair_caught"),
    ptReturned: real("pt_returned"),
    ptReturnYards: real("pt_return_yards"),
    ptReturnTds: real("pt_return_tds"),
    ptNetYards: real("pt_net_yards"),
    fantasyPoints: real("fantasy_points"),
    fantasyPointsPpr: real("fantasy_points_ppr"),
    week: real("week"),
    opponentTeam: text("opponent_team"),
    gwfgDistance: integer("gwfg_distance"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    uniqueIndex("pws_player_game_idx").on(t.playerId, t.gameId),
    index("pws_game_idx").on(t.gameId),
    index("pws_player_idx").on(t.playerId),
  ],
);

export const player_season_stats = sqliteTable(
  "player_season_stats",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").notNull().references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    position: text("position"),
    positionGroup: text("position_group"),
    headshotUrl: text("headshot_url"),
    season: integer("season"),
    seasonType: text("season_type").notNull(),
    completions: integer("completions"),
    attempts: integer("attempts"),
    passingYards: real("passing_yards"),
    passingTds: integer("passing_tds"),
    passingInterceptions: integer("passing_interceptions"),
    sacksSuffered: integer("sacks_suffered"),
    sackYardsLost: real("sack_yards_lost"),
    sackFumbles: integer("sack_fumbles"),
    sackFumblesLost: integer("sack_fumbles_lost"),
    passingAirYards: real("passing_air_yards"),
    passingYardsAfterCatch: real("passing_yards_after_catch"),
    passingFirstDowns: integer("passing_first_downs"),
    passingEpa: real("passing_epa"),
    passingCpoe: real("passing_cpoe"),
    passing2ptConversions: integer("passing_2pt_conversions"),
    pacr: real("pacr"),
    passing10: integer("passing_10"),
    passing16: integer("passing_16"),
    passing20: integer("passing_20"),
    passing40: integer("passing_40"),
    carries: integer("carries"),
    rushingYards: real("rushing_yards"),
    rushingTds: integer("rushing_tds"),
    rushingFumbles: integer("rushing_fumbles"),
    rushingFumblesLost: integer("rushing_fumbles_lost"),
    rushingFirstDowns: integer("rushing_first_downs"),
    rushingEpa: real("rushing_epa"),
    rushing2ptConversions: integer("rushing_2pt_conversions"),
    rushing10: integer("rushing_10"),
    rushing12: integer("rushing_12"),
    rushing20: integer("rushing_20"),
    rushing40: integer("rushing_40"),
    receptions: integer("receptions"),
    targets: integer("targets"),
    receivingYards: integer("receiving_yards"),
    receivingTds: integer("receiving_tds"),
    receivingFumbles: integer("receiving_fumbles"),
    receivingFumblesLost: integer("receiving_fumbles_lost"),
    receivingAirYards: real("receiving_air_yards"),
    receivingYardsAfterCatch: real("receiving_yards_after_catch"),
    receivingFirstDowns: integer("receiving_first_downs"),
    receivingEpa: real("receiving_epa"),
    receiving2ptConversions: integer("receiving_2pt_conversions"),
    receiving10: integer("receiving_10"),
    receiving16: integer("receiving_16"),
    receiving20: integer("receiving_20"),
    receiving40: integer("receiving_40"),
    racr: real("racr"),
    targetShare: real("target_share"),
    airYardsShare: real("air_yards_share"),
    wopr: real("wopr"),
    specialTeamsTds: integer("special_teams_tds"),
    defTacklesSolo: real("def_tackles_solo"),
    defTacklesWithAssist: real("def_tackles_with_assist"),
    defTackleAssists: real("def_tackle_assists"),
    defTacklesForLoss: real("def_tackles_for_loss"),
    defTacklesForLossYards: real("def_tackles_for_loss_yards"),
    defFumblesForced: integer("def_fumbles_forced"),
    defSacks: real("def_sacks"),
    defSackYards: real("def_sack_yards"),
    defQbHits: real("def_qb_hits"),
    defInterceptions: real("def_interceptions"),
    defInterceptionYards: real("def_interception_yards"),
    defPassDefended: real("def_pass_defended"),
    defTds: real("def_tds"),
    defFumbles: real("def_fumbles"),
    defSafeties: real("def_safeties"),
    defPuntBlocks: real("def_punt_blocks"),
    defPatBlocks: real("def_pat_blocks"),
    defFgBlocks: real("def_fg_blocks"),
    def2ptAtts: real("def_2pt_atts"),
    def2ptMade: real("def_2pt_made"),
    miscYards: real("misc_yards"),
    fumbleRecoveryOwn: real("fumble_recovery_own"),
    fumbleRecoveryYardsOwn: real("fumble_recovery_yards_own"),
    fumbleRecoveryOpp: real("fumble_recovery_opp"),
    fumbleRecoveryYardsOpp: real("fumble_recovery_yards_opp"),
    fumbleRecoveryTds: real("fumble_recovery_tds"),
    penalties: real("penalties"),
    penaltyYards: real("penalty_yards"),
    timeouts: real("timeouts"),
    fumblesForcedByOpp: real("fumbles_forced_by_opp"),
    fumblesNotForced: real("fumbles_not_forced"),
    fumblesOutOfBounds: real("fumbles_out_of_bounds"),
    fumblesTotal: real("fumbles_total"),
    fumblesLostTotal: real("fumbles_lost_total"),
    puntReturns: real("punt_returns"),
    puntReturnYards: real("punt_return_yards"),
    kickoffReturns: real("kickoff_returns"),
    kickoffReturnYards: real("kickoff_return_yards"),
    fgMade: real("fg_made"),
    fgAtt: real("fg_att"),
    fgMissed: real("fg_missed"),
    fgBlocked: real("fg_blocked"),
    fgLong: real("fg_long"),
    fgPct: real("fg_pct"),
    fgMade019: real("fg_made_0_19"),
    fgMade2029: real("fg_made_20_29"),
    fgMade3039: real("fg_made_30_39"),
    fgMade4049: real("fg_made_40_49"),
    fgMade5059: real("fg_made_50_59"),
    fgMade60_: real("fg_made_60_"),
    fgMissed019: real("fg_missed_0_19"),
    fgMissed2029: real("fg_missed_20_29"),
    fgMissed3039: real("fg_missed_30_39"),
    fgMissed4049: real("fg_missed_40_49"),
    fgMissed5059: real("fg_missed_50_59"),
    fgMissed60_: real("fg_missed_60_"),
    fgMadeList: text("fg_made_list", { mode: "json" }).$type<number[]>().notNull(),
    fgMissedList: text("fg_missed_list", { mode: "json" }).$type<number[]>().notNull(),
    fgBlockedList: text("fg_blocked_list", { mode: "json" }).$type<number[]>().notNull(),
    fgMadeDistance: real("fg_made_distance"),
    fgMissedDistance: real("fg_missed_distance"),
    fgBlockedDistance: real("fg_blocked_distance"),
    patMade: real("pat_made"),
    patAtt: real("pat_att"),
    patMissed: real("pat_missed"),
    patBlocked: real("pat_blocked"),
    patPct: real("pat_pct"),
    gwfgMade: real("gwfg_made"),
    gwfgAtt: real("gwfg_att"),
    gwfgMissed: real("gwfg_missed"),
    gwfgBlocked: real("gwfg_blocked"),
    ptAtt: real("pt_att"),
    ptBlocked: real("pt_blocked"),
    ptLong: real("pt_long"),
    ptYards: real("pt_yards"),
    ptInside20: real("pt_inside_20"),
    ptOutOfBounds: real("pt_out_of_bounds"),
    ptDowned: real("pt_downed"),
    ptTouchback: real("pt_touchback"),
    ptFairCaught: real("pt_fair_caught"),
    ptReturned: real("pt_returned"),
    ptReturnYards: real("pt_return_yards"),
    ptReturnTds: real("pt_return_tds"),
    ptNetYards: real("pt_net_yards"),
    fantasyPoints: real("fantasy_points"),
    fantasyPointsPpr: real("fantasy_points_ppr"),
    games: integer("games"),
    gwfgDistanceList: text("gwfg_distance_list", { mode: "json" }).$type<number[]>().notNull(),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    uniqueIndex("pss_player_season_idx").on(t.playerId, t.season, t.seasonType),
    index("pss_player_idx").on(t.playerId),
  ],
);
