import { sqliteTable, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core";

export const team = sqliteTable(
  "team",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    slug: text("slug").notNull(),
    abbr: text("team_abbr"),
    name: text("team_name"),
    nick: text("team_nick"),
    conference: text("team_conf"),
    division: text("team_division"),
    teamColor: text("team_color").notNull(),
    teamColor2: text("team_color2").notNull(),
    teamColor3: text("team_color3"),
    teamColor4: text("team_color4"),
    teamLogoWikipedia: text("team_logo_wikipedia").notNull(),
    teamLogoEspn: text("team_logo_espn").notNull(),
    teamWordmark: text("team_wordmark").notNull(),
    teamLogoSquared: text("team_logo_squared").notNull(),
    teamConferenceLogo: text("team_conference_logo").notNull(),
    teamLeagueLogo: text("team_league_logo").notNull(),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [uniqueIndex("team_slug_idx").on(t.slug), uniqueIndex("team_abbr_idx").on(t.abbr)],
);

export const player = sqliteTable(
  "player",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    latestTeamId: integer("latest_team_id").references(() => team.id),
    slug: text("slug").notNull(),
    displayName: text("display_name"),
    commonFirstName: text("common_first_name"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    shortName: text("short_name"),
    footballName: text("football_name"),
    suffix: text("suffix"),
    birthDate: integer("birth_date", { mode: "timestamp_ms" }),
    positionGroup: text("position_group"),
    position: text("position"),
    ngsPositionGroup: text("ngs_position_group"),
    ngsPosition: text("ngs_position"),
    height: integer("height"),
    weight: integer("weight"),
    headshot: text("headshot"),
    collegeName: text("college_name"),
    collegeConference: text("college_conference"),
    jerseyNumber: text("jersey_number"),
    rookieSeason: integer("rookie_season"),
    lastSeason: integer("last_season"),
    status: text("status"),
    ngsStatus: text("ngs_status"),
    ngsStatusShortDescription: text("ngs_status_short_description"),
    yearsOfExperience: integer("years_of_experience"),
    pffPosition: text("pff_position"),
    pffStatus: text("pff_status"),
    draftYear: integer("draft_year"),
    draftRound: integer("draft_round"),
    draftPick: integer("draft_pick"),
    draftTeam: text("draft_team"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    uniqueIndex("player_slug_idx").on(t.slug),
    index("player_team_idx").on(t.latestTeamId),
    index("player_position_idx").on(t.position),
  ],
);

export const official = sqliteTable(
  "official",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    position: text("position"),
    jerseyNumber: text("jersey_number"),
  },
  (t) => [uniqueIndex("official_slug_idx").on(t.slug)],
);
