import { defineRelations } from "drizzle-orm";
import * as charting from "./charting";
import * as contracts from "./contracts";
import * as draftCombine from "./draft-combine";
import * as espnQbr from "./espn-qbr";
import * as external from "./external";
import * as games from "./games";
import * as injuries from "./injuries";
import * as ngs from "./ngs";
import * as pfrAdvstats from "./pfr-advstats";
import * as play from "./play";
import * as playerStats from "./player-stats";
import * as reference from "./reference";
import * as snapsRosters from "./snaps-rosters";
import * as teamStats from "./team-stats";
import * as trades from "./trades";

const schema = {
  ...charting,
  ...contracts,
  ...draftCombine,
  ...espnQbr,
  ...external,
  ...games,
  ...injuries,
  ...ngs,
  ...pfrAdvstats,
  ...play,
  ...playerStats,
  ...reference,
  ...snapsRosters,
  ...teamStats,
  ...trades,
};

export const relations = defineRelations(schema, (r) => ({
  coach: {
    gameCoachAsCoach: r.many.gameCoach({ from: r.coach.id, to: r.gameCoach.coachId, alias: "gameCoach_coach" }),
  },
  college: {
    draftPickAsCollege: r.many.draftPick({ from: r.college.id, to: r.draftPick.collegeId, alias: "draftPick_college" }),
    combineResultAsCollege: r.many.combineResult({ from: r.college.id, to: r.combineResult.collegeId, alias: "combineResult_college" }),
    playerAsCollege: r.many.player({ from: r.college.id, to: r.player.collegeId, alias: "player_college" }),
  },
  combineResult: {
    player: r.one.player({ from: r.combineResult.playerId, to: r.player.id, alias: "combineResult_player", optional: true }),
    college: r.one.college({ from: r.combineResult.collegeId, to: r.college.id, alias: "combineResult_college", optional: true }),
    draftPick: r.one.draftPick({ from: r.combineResult.draftPickId, to: r.draftPick.id, alias: "combineResult_draftPick", optional: true }),
  },
  contract: {
    player: r.one.player({ from: r.contract.playerId, to: r.player.id, alias: "contract_player", optional: true }),
    contractHistoryAsContract: r.many.contractHistory({ from: r.contract.id, to: r.contractHistory.contractId, alias: "contractHistory_contract" }),
  },
  contractHistory: {
    contract: r.one.contract({ from: r.contractHistory.contractId, to: r.contract.id, alias: "contractHistory_contract", optional: true }),
  },
  draftPick: {
    season: r.one.season({ from: r.draftPick.seasonId, to: r.season.id, alias: "draftPick_season", optional: true }),
    team: r.one.team({ from: r.draftPick.teamId, to: r.team.id, alias: "draftPick_team", optional: true }),
    player: r.one.player({ from: r.draftPick.playerId, to: r.player.id, alias: "draftPick_player", optional: true }),
    college: r.one.college({ from: r.draftPick.collegeId, to: r.college.id, alias: "draftPick_college", optional: true }),
    position: r.one.position({ from: r.draftPick.positionId, to: r.position.id, alias: "draftPick_position", optional: true }),
    combineResultAsDraftPick: r.many.combineResult({ from: r.draftPick.id, to: r.combineResult.draftPickId, alias: "combineResult_draftPick" }),
  },
  espnQbrSeason: {
    player: r.one.player({ from: r.espnQbrSeason.playerId, to: r.player.id, alias: "espnQbrSeason_player", optional: true }),
    season: r.one.season({ from: r.espnQbrSeason.seasonId, to: r.season.id, alias: "espnQbrSeason_season", optional: true }),
  },
  espnQbrWeek: {
    player: r.one.player({ from: r.espnQbrWeek.playerId, to: r.player.id, alias: "espnQbrWeek_player", optional: true }),
    game: r.one.game({ from: r.espnQbrWeek.gameId, to: r.game.id, alias: "espnQbrWeek_game", optional: true }),
  },
  ftnCharting: {
    game: r.one.game({ from: r.ftnCharting.gameId, to: r.game.id, alias: "ftnCharting_game", optional: true }),
    play: r.one.play({ from: r.ftnCharting.playId, to: r.play.id, alias: "ftnCharting_play", optional: true }),
  },
  game: {
    ftnChartingAsGame: r.many.ftnCharting({ from: r.game.id, to: r.ftnCharting.gameId, alias: "ftnCharting_game" }),
    espnQbrWeekAsGame: r.many.espnQbrWeek({ from: r.game.id, to: r.espnQbrWeek.gameId, alias: "espnQbrWeek_game" }),
    season: r.one.season({ from: r.game.seasonId, to: r.season.id, alias: "game_season", optional: true }),
    awayTeam: r.one.team({ from: r.game.awayTeamId, to: r.team.id, alias: "game_awayTeam", optional: true }),
    homeTeam: r.one.team({ from: r.game.homeTeamId, to: r.team.id, alias: "game_homeTeam", optional: true }),
    stadium: r.one.stadium({ from: r.game.stadiumId, to: r.stadium.id, alias: "game_stadium", optional: true }),
    headOfficial: r.one.official({ from: r.game.headOfficialId, to: r.official.id, alias: "game_headOfficial", optional: true }),
    gameParticipantAsGame: r.many.gameParticipant({ from: r.game.id, to: r.gameParticipant.gameId, alias: "gameParticipant_game" }),
    gameCoachAsGame: r.many.gameCoach({ from: r.game.id, to: r.gameCoach.gameId, alias: "gameCoach_game" }),
    gameOfficialAsGame: r.many.gameOfficial({ from: r.game.id, to: r.gameOfficial.gameId, alias: "gameOfficial_game" }),
    pfrAdvDefWeekAsGame: r.many.pfrAdvDefWeek({ from: r.game.id, to: r.pfrAdvDefWeek.gameId, alias: "pfrAdvDefWeek_game" }),
    pfrAdvPassWeekAsGame: r.many.pfrAdvPassWeek({ from: r.game.id, to: r.pfrAdvPassWeek.gameId, alias: "pfrAdvPassWeek_game" }),
    pfrAdvRecWeekAsGame: r.many.pfrAdvRecWeek({ from: r.game.id, to: r.pfrAdvRecWeek.gameId, alias: "pfrAdvRecWeek_game" }),
    pfrAdvRushWeekAsGame: r.many.pfrAdvRushWeek({ from: r.game.id, to: r.pfrAdvRushWeek.gameId, alias: "pfrAdvRushWeek_game" }),
    playAsGame: r.many.play({ from: r.game.id, to: r.play.gameId, alias: "play_game" }),
    playerGamePassingStatsAsGame: r.many.playerGamePassingStats({ from: r.game.id, to: r.playerGamePassingStats.gameId, alias: "playerGamePassingStats_game" }),
    playerGameRushingStatsAsGame: r.many.playerGameRushingStats({ from: r.game.id, to: r.playerGameRushingStats.gameId, alias: "playerGameRushingStats_game" }),
    playerGameReceivingStatsAsGame: r.many.playerGameReceivingStats({ from: r.game.id, to: r.playerGameReceivingStats.gameId, alias: "playerGameReceivingStats_game" }),
    playerGameDefenseStatsAsGame: r.many.playerGameDefenseStats({ from: r.game.id, to: r.playerGameDefenseStats.gameId, alias: "playerGameDefenseStats_game" }),
    playerGameKickingStatsAsGame: r.many.playerGameKickingStats({ from: r.game.id, to: r.playerGameKickingStats.gameId, alias: "playerGameKickingStats_game" }),
    playerGamePuntingStatsAsGame: r.many.playerGamePuntingStats({ from: r.game.id, to: r.playerGamePuntingStats.gameId, alias: "playerGamePuntingStats_game" }),
    playerGameReturnStatsAsGame: r.many.playerGameReturnStats({ from: r.game.id, to: r.playerGameReturnStats.gameId, alias: "playerGameReturnStats_game" }),
    playerGameMiscStatsAsGame: r.many.playerGameMiscStats({ from: r.game.id, to: r.playerGameMiscStats.gameId, alias: "playerGameMiscStats_game" }),
    snapCountAsGame: r.many.snapCount({ from: r.game.id, to: r.snapCount.gameId, alias: "snapCount_game" }),
    teamGameStatsAsGame: r.many.teamGameStats({ from: r.game.id, to: r.teamGameStats.gameId, alias: "teamGameStats_game" }),
  },
  gameCoach: {
    game: r.one.game({ from: r.gameCoach.gameId, to: r.game.id, alias: "gameCoach_game", optional: true }),
    coach: r.one.coach({ from: r.gameCoach.coachId, to: r.coach.id, alias: "gameCoach_coach", optional: true }),
    team: r.one.team({ from: r.gameCoach.teamId, to: r.team.id, alias: "gameCoach_team", optional: true }),
  },
  gameOfficial: {
    game: r.one.game({ from: r.gameOfficial.gameId, to: r.game.id, alias: "gameOfficial_game", optional: true }),
    official: r.one.official({ from: r.gameOfficial.officialId, to: r.official.id, alias: "gameOfficial_official", optional: true }),
  },
  gameParticipant: {
    game: r.one.game({ from: r.gameParticipant.gameId, to: r.game.id, alias: "gameParticipant_game", optional: true }),
    player: r.one.player({ from: r.gameParticipant.playerId, to: r.player.id, alias: "gameParticipant_player", optional: true }),
    team: r.one.team({ from: r.gameParticipant.teamId, to: r.team.id, alias: "gameParticipant_team", optional: true }),
  },
  injuryReport: {
    player: r.one.player({ from: r.injuryReport.playerId, to: r.player.id, alias: "injuryReport_player", optional: true }),
    team: r.one.team({ from: r.injuryReport.teamId, to: r.team.id, alias: "injuryReport_team", optional: true }),
    season: r.one.season({ from: r.injuryReport.seasonId, to: r.season.id, alias: "injuryReport_season", optional: true }),
    week: r.one.week({ from: r.injuryReport.weekId, to: r.week.id, alias: "injuryReport_week", optional: true }),
  },
  ngsPassing: {
    player: r.one.player({ from: r.ngsPassing.playerId, to: r.player.id, alias: "ngsPassing_player", optional: true }),
    team: r.one.team({ from: r.ngsPassing.teamId, to: r.team.id, alias: "ngsPassing_team", optional: true }),
    season: r.one.season({ from: r.ngsPassing.seasonId, to: r.season.id, alias: "ngsPassing_season", optional: true }),
    week: r.one.week({ from: r.ngsPassing.weekId, to: r.week.id, alias: "ngsPassing_week", optional: true }),
  },
  ngsReceiving: {
    player: r.one.player({ from: r.ngsReceiving.playerId, to: r.player.id, alias: "ngsReceiving_player", optional: true }),
    team: r.one.team({ from: r.ngsReceiving.teamId, to: r.team.id, alias: "ngsReceiving_team", optional: true }),
    season: r.one.season({ from: r.ngsReceiving.seasonId, to: r.season.id, alias: "ngsReceiving_season", optional: true }),
    week: r.one.week({ from: r.ngsReceiving.weekId, to: r.week.id, alias: "ngsReceiving_week", optional: true }),
  },
  ngsRushing: {
    player: r.one.player({ from: r.ngsRushing.playerId, to: r.player.id, alias: "ngsRushing_player", optional: true }),
    team: r.one.team({ from: r.ngsRushing.teamId, to: r.team.id, alias: "ngsRushing_team", optional: true }),
    season: r.one.season({ from: r.ngsRushing.seasonId, to: r.season.id, alias: "ngsRushing_season", optional: true }),
    week: r.one.week({ from: r.ngsRushing.weekId, to: r.week.id, alias: "ngsRushing_week", optional: true }),
  },
  official: {
    gameAsHeadOfficial: r.many.game({ from: r.official.id, to: r.game.headOfficialId, alias: "game_headOfficial" }),
    gameOfficialAsOfficial: r.many.gameOfficial({ from: r.official.id, to: r.gameOfficial.officialId, alias: "gameOfficial_official" }),
  },
  pfrAdvDefSeason: {
    player: r.one.player({ from: r.pfrAdvDefSeason.playerId, to: r.player.id, alias: "pfrAdvDefSeason_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvDefSeason.teamId, to: r.team.id, alias: "pfrAdvDefSeason_team", optional: true }),
    season: r.one.season({ from: r.pfrAdvDefSeason.seasonId, to: r.season.id, alias: "pfrAdvDefSeason_season", optional: true }),
  },
  pfrAdvDefWeek: {
    player: r.one.player({ from: r.pfrAdvDefWeek.playerId, to: r.player.id, alias: "pfrAdvDefWeek_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvDefWeek.teamId, to: r.team.id, alias: "pfrAdvDefWeek_team", optional: true }),
    game: r.one.game({ from: r.pfrAdvDefWeek.gameId, to: r.game.id, alias: "pfrAdvDefWeek_game", optional: true }),
  },
  pfrAdvPassSeason: {
    player: r.one.player({ from: r.pfrAdvPassSeason.playerId, to: r.player.id, alias: "pfrAdvPassSeason_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvPassSeason.teamId, to: r.team.id, alias: "pfrAdvPassSeason_team", optional: true }),
    season: r.one.season({ from: r.pfrAdvPassSeason.seasonId, to: r.season.id, alias: "pfrAdvPassSeason_season", optional: true }),
  },
  pfrAdvPassWeek: {
    player: r.one.player({ from: r.pfrAdvPassWeek.playerId, to: r.player.id, alias: "pfrAdvPassWeek_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvPassWeek.teamId, to: r.team.id, alias: "pfrAdvPassWeek_team", optional: true }),
    game: r.one.game({ from: r.pfrAdvPassWeek.gameId, to: r.game.id, alias: "pfrAdvPassWeek_game", optional: true }),
  },
  pfrAdvRecSeason: {
    player: r.one.player({ from: r.pfrAdvRecSeason.playerId, to: r.player.id, alias: "pfrAdvRecSeason_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvRecSeason.teamId, to: r.team.id, alias: "pfrAdvRecSeason_team", optional: true }),
    season: r.one.season({ from: r.pfrAdvRecSeason.seasonId, to: r.season.id, alias: "pfrAdvRecSeason_season", optional: true }),
  },
  pfrAdvRecWeek: {
    player: r.one.player({ from: r.pfrAdvRecWeek.playerId, to: r.player.id, alias: "pfrAdvRecWeek_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvRecWeek.teamId, to: r.team.id, alias: "pfrAdvRecWeek_team", optional: true }),
    game: r.one.game({ from: r.pfrAdvRecWeek.gameId, to: r.game.id, alias: "pfrAdvRecWeek_game", optional: true }),
  },
  pfrAdvRushSeason: {
    player: r.one.player({ from: r.pfrAdvRushSeason.playerId, to: r.player.id, alias: "pfrAdvRushSeason_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvRushSeason.teamId, to: r.team.id, alias: "pfrAdvRushSeason_team", optional: true }),
    season: r.one.season({ from: r.pfrAdvRushSeason.seasonId, to: r.season.id, alias: "pfrAdvRushSeason_season", optional: true }),
  },
  pfrAdvRushWeek: {
    player: r.one.player({ from: r.pfrAdvRushWeek.playerId, to: r.player.id, alias: "pfrAdvRushWeek_player", optional: true }),
    team: r.one.team({ from: r.pfrAdvRushWeek.teamId, to: r.team.id, alias: "pfrAdvRushWeek_team", optional: true }),
    game: r.one.game({ from: r.pfrAdvRushWeek.gameId, to: r.game.id, alias: "pfrAdvRushWeek_game", optional: true }),
  },
  play: {
    ftnChartingAsPlay: r.many.ftnCharting({ from: r.play.id, to: r.ftnCharting.playId, alias: "ftnCharting_play" }),
    game: r.one.game({ from: r.play.gameId, to: r.game.id, alias: "play_game", optional: true }),
    possessionTeam: r.one.team({ from: r.play.possessionTeamId, to: r.team.id, alias: "play_possessionTeam", optional: true }),
    defensiveTeam: r.one.team({ from: r.play.defensiveTeamId, to: r.team.id, alias: "play_defensiveTeam", optional: true }),
    playTeamStatsAsPlay: r.many.playTeamStats({ from: r.play.id, to: r.playTeamStats.playId, alias: "playTeamStats_play" }),
    playPlayerAsPlay: r.many.playPlayer({ from: r.play.id, to: r.playPlayer.playId, alias: "playPlayer_play" }),
    playTeamAsPlay: r.many.playTeam({ from: r.play.id, to: r.playTeam.playId, alias: "playTeam_play" }),
  },
  playPlayer: {
    play: r.one.play({ from: r.playPlayer.playId, to: r.play.id, alias: "playPlayer_play", optional: true }),
    player: r.one.player({ from: r.playPlayer.playerId, to: r.player.id, alias: "playPlayer_player", optional: true }),
    team: r.one.team({ from: r.playPlayer.teamId, to: r.team.id, alias: "playPlayer_team", optional: true }),
  },
  playTeam: {
    play: r.one.play({ from: r.playTeam.playId, to: r.play.id, alias: "playTeam_play", optional: true }),
    team: r.one.team({ from: r.playTeam.teamId, to: r.team.id, alias: "playTeam_team", optional: true }),
  },
  playTeamStats: {
    play: r.one.play({ from: r.playTeamStats.playId, to: r.play.id, alias: "playTeamStats_play", optional: true }),
    team: r.one.team({ from: r.playTeamStats.teamId, to: r.team.id, alias: "playTeamStats_team", optional: true }),
  },
  player: {
    contractAsPlayer: r.many.contract({ from: r.player.id, to: r.contract.playerId, alias: "contract_player" }),
    draftPickAsPlayer: r.many.draftPick({ from: r.player.id, to: r.draftPick.playerId, alias: "draftPick_player" }),
    combineResultAsPlayer: r.many.combineResult({ from: r.player.id, to: r.combineResult.playerId, alias: "combineResult_player" }),
    espnQbrSeasonAsPlayer: r.many.espnQbrSeason({ from: r.player.id, to: r.espnQbrSeason.playerId, alias: "espnQbrSeason_player" }),
    espnQbrWeekAsPlayer: r.many.espnQbrWeek({ from: r.player.id, to: r.espnQbrWeek.playerId, alias: "espnQbrWeek_player" }),
    gameParticipantAsPlayer: r.many.gameParticipant({ from: r.player.id, to: r.gameParticipant.playerId, alias: "gameParticipant_player" }),
    injuryReportAsPlayer: r.many.injuryReport({ from: r.player.id, to: r.injuryReport.playerId, alias: "injuryReport_player" }),
    ngsPassingAsPlayer: r.many.ngsPassing({ from: r.player.id, to: r.ngsPassing.playerId, alias: "ngsPassing_player" }),
    ngsReceivingAsPlayer: r.many.ngsReceiving({ from: r.player.id, to: r.ngsReceiving.playerId, alias: "ngsReceiving_player" }),
    ngsRushingAsPlayer: r.many.ngsRushing({ from: r.player.id, to: r.ngsRushing.playerId, alias: "ngsRushing_player" }),
    pfrAdvDefSeasonAsPlayer: r.many.pfrAdvDefSeason({ from: r.player.id, to: r.pfrAdvDefSeason.playerId, alias: "pfrAdvDefSeason_player" }),
    pfrAdvPassSeasonAsPlayer: r.many.pfrAdvPassSeason({ from: r.player.id, to: r.pfrAdvPassSeason.playerId, alias: "pfrAdvPassSeason_player" }),
    pfrAdvRushSeasonAsPlayer: r.many.pfrAdvRushSeason({ from: r.player.id, to: r.pfrAdvRushSeason.playerId, alias: "pfrAdvRushSeason_player" }),
    pfrAdvRecSeasonAsPlayer: r.many.pfrAdvRecSeason({ from: r.player.id, to: r.pfrAdvRecSeason.playerId, alias: "pfrAdvRecSeason_player" }),
    pfrAdvDefWeekAsPlayer: r.many.pfrAdvDefWeek({ from: r.player.id, to: r.pfrAdvDefWeek.playerId, alias: "pfrAdvDefWeek_player" }),
    pfrAdvPassWeekAsPlayer: r.many.pfrAdvPassWeek({ from: r.player.id, to: r.pfrAdvPassWeek.playerId, alias: "pfrAdvPassWeek_player" }),
    pfrAdvRecWeekAsPlayer: r.many.pfrAdvRecWeek({ from: r.player.id, to: r.pfrAdvRecWeek.playerId, alias: "pfrAdvRecWeek_player" }),
    pfrAdvRushWeekAsPlayer: r.many.pfrAdvRushWeek({ from: r.player.id, to: r.pfrAdvRushWeek.playerId, alias: "pfrAdvRushWeek_player" }),
    playPlayerAsPlayer: r.many.playPlayer({ from: r.player.id, to: r.playPlayer.playerId, alias: "playPlayer_player" }),
    playerGamePassingStatsAsPlayer: r.many.playerGamePassingStats({ from: r.player.id, to: r.playerGamePassingStats.playerId, alias: "playerGamePassingStats_player" }),
    playerSeasonPassingStatsAsPlayer: r.many.playerSeasonPassingStats({ from: r.player.id, to: r.playerSeasonPassingStats.playerId, alias: "playerSeasonPassingStats_player" }),
    playerGameRushingStatsAsPlayer: r.many.playerGameRushingStats({ from: r.player.id, to: r.playerGameRushingStats.playerId, alias: "playerGameRushingStats_player" }),
    playerSeasonRushingStatsAsPlayer: r.many.playerSeasonRushingStats({ from: r.player.id, to: r.playerSeasonRushingStats.playerId, alias: "playerSeasonRushingStats_player" }),
    playerGameReceivingStatsAsPlayer: r.many.playerGameReceivingStats({ from: r.player.id, to: r.playerGameReceivingStats.playerId, alias: "playerGameReceivingStats_player" }),
    playerSeasonReceivingStatsAsPlayer: r.many.playerSeasonReceivingStats({ from: r.player.id, to: r.playerSeasonReceivingStats.playerId, alias: "playerSeasonReceivingStats_player" }),
    playerGameDefenseStatsAsPlayer: r.many.playerGameDefenseStats({ from: r.player.id, to: r.playerGameDefenseStats.playerId, alias: "playerGameDefenseStats_player" }),
    playerSeasonDefenseStatsAsPlayer: r.many.playerSeasonDefenseStats({ from: r.player.id, to: r.playerSeasonDefenseStats.playerId, alias: "playerSeasonDefenseStats_player" }),
    playerGameKickingStatsAsPlayer: r.many.playerGameKickingStats({ from: r.player.id, to: r.playerGameKickingStats.playerId, alias: "playerGameKickingStats_player" }),
    playerSeasonKickingStatsAsPlayer: r.many.playerSeasonKickingStats({ from: r.player.id, to: r.playerSeasonKickingStats.playerId, alias: "playerSeasonKickingStats_player" }),
    playerGamePuntingStatsAsPlayer: r.many.playerGamePuntingStats({ from: r.player.id, to: r.playerGamePuntingStats.playerId, alias: "playerGamePuntingStats_player" }),
    playerSeasonPuntingStatsAsPlayer: r.many.playerSeasonPuntingStats({ from: r.player.id, to: r.playerSeasonPuntingStats.playerId, alias: "playerSeasonPuntingStats_player" }),
    playerGameReturnStatsAsPlayer: r.many.playerGameReturnStats({ from: r.player.id, to: r.playerGameReturnStats.playerId, alias: "playerGameReturnStats_player" }),
    playerSeasonReturnStatsAsPlayer: r.many.playerSeasonReturnStats({ from: r.player.id, to: r.playerSeasonReturnStats.playerId, alias: "playerSeasonReturnStats_player" }),
    playerGameMiscStatsAsPlayer: r.many.playerGameMiscStats({ from: r.player.id, to: r.playerGameMiscStats.playerId, alias: "playerGameMiscStats_player" }),
    playerSeasonMiscStatsAsPlayer: r.many.playerSeasonMiscStats({ from: r.player.id, to: r.playerSeasonMiscStats.playerId, alias: "playerSeasonMiscStats_player" }),
    college: r.one.college({ from: r.player.collegeId, to: r.college.id, alias: "player_college", optional: true }),
    latestTeam: r.one.team({ from: r.player.latestTeamId, to: r.team.id, alias: "player_latestTeam", optional: true }),
    playerPositionAsPlayer: r.many.playerPosition({ from: r.player.id, to: r.playerPosition.playerId, alias: "playerPosition_player" }),
    playerBodyMeasurementAsPlayer: r.many.playerBodyMeasurement({ from: r.player.id, to: r.playerBodyMeasurement.playerId, alias: "playerBodyMeasurement_player" }),
    playerJerseyNumberAsPlayer: r.many.playerJerseyNumber({ from: r.player.id, to: r.playerJerseyNumber.playerId, alias: "playerJerseyNumber_player" }),
    playerCareerStatsAsPlayer: r.many.playerCareerStats({ from: r.player.id, to: r.playerCareerStats.playerId, alias: "playerCareerStats_player" }),
    playerCollegeStatsAsPlayer: r.many.playerCollegeStats({ from: r.player.id, to: r.playerCollegeStats.playerId, alias: "playerCollegeStats_player" }),
    snapCountAsPlayer: r.many.snapCount({ from: r.player.id, to: r.snapCount.playerId, alias: "snapCount_player" }),
    rosterDepthChartAsPlayer: r.many.rosterDepthChart({ from: r.player.id, to: r.rosterDepthChart.playerId, alias: "rosterDepthChart_player" }),
    tradePlayerAsTradedPlayer: r.many.tradePlayer({ from: r.player.id, to: r.tradePlayer.tradedPlayerId, alias: "tradePlayer_tradedPlayer" }),
  },
  playerBodyMeasurement: {
    player: r.one.player({ from: r.playerBodyMeasurement.playerId, to: r.player.id, alias: "playerBodyMeasurement_player", optional: true }),
    season: r.one.season({ from: r.playerBodyMeasurement.seasonId, to: r.season.id, alias: "playerBodyMeasurement_season", optional: true }),
  },
  playerCareerStats: {
    player: r.one.player({ from: r.playerCareerStats.playerId, to: r.player.id, alias: "playerCareerStats_player", optional: true }),
  },
  playerCollegeStats: {
    player: r.one.player({ from: r.playerCollegeStats.playerId, to: r.player.id, alias: "playerCollegeStats_player", optional: true }),
  },
  playerGameDefenseStats: {
    player: r.one.player({ from: r.playerGameDefenseStats.playerId, to: r.player.id, alias: "playerGameDefenseStats_player", optional: true }),
    team: r.one.team({ from: r.playerGameDefenseStats.teamId, to: r.team.id, alias: "playerGameDefenseStats_team", optional: true }),
    game: r.one.game({ from: r.playerGameDefenseStats.gameId, to: r.game.id, alias: "playerGameDefenseStats_game", optional: true }),
  },
  playerGameKickingStats: {
    player: r.one.player({ from: r.playerGameKickingStats.playerId, to: r.player.id, alias: "playerGameKickingStats_player", optional: true }),
    team: r.one.team({ from: r.playerGameKickingStats.teamId, to: r.team.id, alias: "playerGameKickingStats_team", optional: true }),
    game: r.one.game({ from: r.playerGameKickingStats.gameId, to: r.game.id, alias: "playerGameKickingStats_game", optional: true }),
  },
  playerGameMiscStats: {
    player: r.one.player({ from: r.playerGameMiscStats.playerId, to: r.player.id, alias: "playerGameMiscStats_player", optional: true }),
    team: r.one.team({ from: r.playerGameMiscStats.teamId, to: r.team.id, alias: "playerGameMiscStats_team", optional: true }),
    game: r.one.game({ from: r.playerGameMiscStats.gameId, to: r.game.id, alias: "playerGameMiscStats_game", optional: true }),
  },
  playerGamePassingStats: {
    player: r.one.player({ from: r.playerGamePassingStats.playerId, to: r.player.id, alias: "playerGamePassingStats_player", optional: true }),
    team: r.one.team({ from: r.playerGamePassingStats.teamId, to: r.team.id, alias: "playerGamePassingStats_team", optional: true }),
    game: r.one.game({ from: r.playerGamePassingStats.gameId, to: r.game.id, alias: "playerGamePassingStats_game", optional: true }),
  },
  playerGamePuntingStats: {
    player: r.one.player({ from: r.playerGamePuntingStats.playerId, to: r.player.id, alias: "playerGamePuntingStats_player", optional: true }),
    team: r.one.team({ from: r.playerGamePuntingStats.teamId, to: r.team.id, alias: "playerGamePuntingStats_team", optional: true }),
    game: r.one.game({ from: r.playerGamePuntingStats.gameId, to: r.game.id, alias: "playerGamePuntingStats_game", optional: true }),
  },
  playerGameReceivingStats: {
    player: r.one.player({ from: r.playerGameReceivingStats.playerId, to: r.player.id, alias: "playerGameReceivingStats_player", optional: true }),
    team: r.one.team({ from: r.playerGameReceivingStats.teamId, to: r.team.id, alias: "playerGameReceivingStats_team", optional: true }),
    game: r.one.game({ from: r.playerGameReceivingStats.gameId, to: r.game.id, alias: "playerGameReceivingStats_game", optional: true }),
  },
  playerGameReturnStats: {
    player: r.one.player({ from: r.playerGameReturnStats.playerId, to: r.player.id, alias: "playerGameReturnStats_player", optional: true }),
    team: r.one.team({ from: r.playerGameReturnStats.teamId, to: r.team.id, alias: "playerGameReturnStats_team", optional: true }),
    game: r.one.game({ from: r.playerGameReturnStats.gameId, to: r.game.id, alias: "playerGameReturnStats_game", optional: true }),
  },
  playerGameRushingStats: {
    player: r.one.player({ from: r.playerGameRushingStats.playerId, to: r.player.id, alias: "playerGameRushingStats_player", optional: true }),
    team: r.one.team({ from: r.playerGameRushingStats.teamId, to: r.team.id, alias: "playerGameRushingStats_team", optional: true }),
    game: r.one.game({ from: r.playerGameRushingStats.gameId, to: r.game.id, alias: "playerGameRushingStats_game", optional: true }),
  },
  playerJerseyNumber: {
    player: r.one.player({ from: r.playerJerseyNumber.playerId, to: r.player.id, alias: "playerJerseyNumber_player", optional: true }),
    season: r.one.season({ from: r.playerJerseyNumber.seasonId, to: r.season.id, alias: "playerJerseyNumber_season", optional: true }),
    week: r.one.week({ from: r.playerJerseyNumber.weekId, to: r.week.id, alias: "playerJerseyNumber_week", optional: true }),
  },
  playerPosition: {
    player: r.one.player({ from: r.playerPosition.playerId, to: r.player.id, alias: "playerPosition_player", optional: true }),
    season: r.one.season({ from: r.playerPosition.seasonId, to: r.season.id, alias: "playerPosition_season", optional: true }),
    week: r.one.week({ from: r.playerPosition.weekId, to: r.week.id, alias: "playerPosition_week", optional: true }),
    position: r.one.position({ from: r.playerPosition.positionId, to: r.position.id, alias: "playerPosition_position", optional: true }),
  },
  playerSeasonDefenseStats: {
    player: r.one.player({ from: r.playerSeasonDefenseStats.playerId, to: r.player.id, alias: "playerSeasonDefenseStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonDefenseStats.teamId, to: r.team.id, alias: "playerSeasonDefenseStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonDefenseStats.seasonId, to: r.season.id, alias: "playerSeasonDefenseStats_season", optional: true }),
  },
  playerSeasonKickingStats: {
    player: r.one.player({ from: r.playerSeasonKickingStats.playerId, to: r.player.id, alias: "playerSeasonKickingStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonKickingStats.teamId, to: r.team.id, alias: "playerSeasonKickingStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonKickingStats.seasonId, to: r.season.id, alias: "playerSeasonKickingStats_season", optional: true }),
  },
  playerSeasonMiscStats: {
    player: r.one.player({ from: r.playerSeasonMiscStats.playerId, to: r.player.id, alias: "playerSeasonMiscStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonMiscStats.teamId, to: r.team.id, alias: "playerSeasonMiscStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonMiscStats.seasonId, to: r.season.id, alias: "playerSeasonMiscStats_season", optional: true }),
  },
  playerSeasonPassingStats: {
    player: r.one.player({ from: r.playerSeasonPassingStats.playerId, to: r.player.id, alias: "playerSeasonPassingStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonPassingStats.teamId, to: r.team.id, alias: "playerSeasonPassingStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonPassingStats.seasonId, to: r.season.id, alias: "playerSeasonPassingStats_season", optional: true }),
  },
  playerSeasonPuntingStats: {
    player: r.one.player({ from: r.playerSeasonPuntingStats.playerId, to: r.player.id, alias: "playerSeasonPuntingStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonPuntingStats.teamId, to: r.team.id, alias: "playerSeasonPuntingStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonPuntingStats.seasonId, to: r.season.id, alias: "playerSeasonPuntingStats_season", optional: true }),
  },
  playerSeasonReceivingStats: {
    player: r.one.player({ from: r.playerSeasonReceivingStats.playerId, to: r.player.id, alias: "playerSeasonReceivingStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonReceivingStats.teamId, to: r.team.id, alias: "playerSeasonReceivingStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonReceivingStats.seasonId, to: r.season.id, alias: "playerSeasonReceivingStats_season", optional: true }),
  },
  playerSeasonReturnStats: {
    player: r.one.player({ from: r.playerSeasonReturnStats.playerId, to: r.player.id, alias: "playerSeasonReturnStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonReturnStats.teamId, to: r.team.id, alias: "playerSeasonReturnStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonReturnStats.seasonId, to: r.season.id, alias: "playerSeasonReturnStats_season", optional: true }),
  },
  playerSeasonRushingStats: {
    player: r.one.player({ from: r.playerSeasonRushingStats.playerId, to: r.player.id, alias: "playerSeasonRushingStats_player", optional: true }),
    team: r.one.team({ from: r.playerSeasonRushingStats.teamId, to: r.team.id, alias: "playerSeasonRushingStats_team", optional: true }),
    season: r.one.season({ from: r.playerSeasonRushingStats.seasonId, to: r.season.id, alias: "playerSeasonRushingStats_season", optional: true }),
  },
  position: {
    draftPickAsPosition: r.many.draftPick({ from: r.position.id, to: r.draftPick.positionId, alias: "draftPick_position" }),
    playerPositionAsPosition: r.many.playerPosition({ from: r.position.id, to: r.playerPosition.positionId, alias: "playerPosition_position" }),
    snapCountAsPosition: r.many.snapCount({ from: r.position.id, to: r.snapCount.positionId, alias: "snapCount_position" }),
    rosterDepthChartAsPosition: r.many.rosterDepthChart({ from: r.position.id, to: r.rosterDepthChart.positionId, alias: "rosterDepthChart_position" }),
  },
  rosterDepthChart: {
    player: r.one.player({ from: r.rosterDepthChart.playerId, to: r.player.id, alias: "rosterDepthChart_player", optional: true }),
    team: r.one.team({ from: r.rosterDepthChart.teamId, to: r.team.id, alias: "rosterDepthChart_team", optional: true }),
    season: r.one.season({ from: r.rosterDepthChart.seasonId, to: r.season.id, alias: "rosterDepthChart_season", optional: true }),
    week: r.one.week({ from: r.rosterDepthChart.weekId, to: r.week.id, alias: "rosterDepthChart_week", optional: true }),
    position: r.one.position({ from: r.rosterDepthChart.positionId, to: r.position.id, alias: "rosterDepthChart_position", optional: true }),
  },
  season: {
    draftPickAsSeason: r.many.draftPick({ from: r.season.id, to: r.draftPick.seasonId, alias: "draftPick_season" }),
    espnQbrSeasonAsSeason: r.many.espnQbrSeason({ from: r.season.id, to: r.espnQbrSeason.seasonId, alias: "espnQbrSeason_season" }),
    gameAsSeason: r.many.game({ from: r.season.id, to: r.game.seasonId, alias: "game_season" }),
    injuryReportAsSeason: r.many.injuryReport({ from: r.season.id, to: r.injuryReport.seasonId, alias: "injuryReport_season" }),
    ngsPassingAsSeason: r.many.ngsPassing({ from: r.season.id, to: r.ngsPassing.seasonId, alias: "ngsPassing_season" }),
    ngsReceivingAsSeason: r.many.ngsReceiving({ from: r.season.id, to: r.ngsReceiving.seasonId, alias: "ngsReceiving_season" }),
    ngsRushingAsSeason: r.many.ngsRushing({ from: r.season.id, to: r.ngsRushing.seasonId, alias: "ngsRushing_season" }),
    pfrAdvDefSeasonAsSeason: r.many.pfrAdvDefSeason({ from: r.season.id, to: r.pfrAdvDefSeason.seasonId, alias: "pfrAdvDefSeason_season" }),
    pfrAdvPassSeasonAsSeason: r.many.pfrAdvPassSeason({ from: r.season.id, to: r.pfrAdvPassSeason.seasonId, alias: "pfrAdvPassSeason_season" }),
    pfrAdvRushSeasonAsSeason: r.many.pfrAdvRushSeason({ from: r.season.id, to: r.pfrAdvRushSeason.seasonId, alias: "pfrAdvRushSeason_season" }),
    pfrAdvRecSeasonAsSeason: r.many.pfrAdvRecSeason({ from: r.season.id, to: r.pfrAdvRecSeason.seasonId, alias: "pfrAdvRecSeason_season" }),
    playerSeasonPassingStatsAsSeason: r.many.playerSeasonPassingStats({ from: r.season.id, to: r.playerSeasonPassingStats.seasonId, alias: "playerSeasonPassingStats_season" }),
    playerSeasonRushingStatsAsSeason: r.many.playerSeasonRushingStats({ from: r.season.id, to: r.playerSeasonRushingStats.seasonId, alias: "playerSeasonRushingStats_season" }),
    playerSeasonReceivingStatsAsSeason: r.many.playerSeasonReceivingStats({ from: r.season.id, to: r.playerSeasonReceivingStats.seasonId, alias: "playerSeasonReceivingStats_season" }),
    playerSeasonDefenseStatsAsSeason: r.many.playerSeasonDefenseStats({ from: r.season.id, to: r.playerSeasonDefenseStats.seasonId, alias: "playerSeasonDefenseStats_season" }),
    playerSeasonKickingStatsAsSeason: r.many.playerSeasonKickingStats({ from: r.season.id, to: r.playerSeasonKickingStats.seasonId, alias: "playerSeasonKickingStats_season" }),
    playerSeasonPuntingStatsAsSeason: r.many.playerSeasonPuntingStats({ from: r.season.id, to: r.playerSeasonPuntingStats.seasonId, alias: "playerSeasonPuntingStats_season" }),
    playerSeasonReturnStatsAsSeason: r.many.playerSeasonReturnStats({ from: r.season.id, to: r.playerSeasonReturnStats.seasonId, alias: "playerSeasonReturnStats_season" }),
    playerSeasonMiscStatsAsSeason: r.many.playerSeasonMiscStats({ from: r.season.id, to: r.playerSeasonMiscStats.seasonId, alias: "playerSeasonMiscStats_season" }),
    weekAsSeason: r.many.week({ from: r.season.id, to: r.week.seasonId, alias: "week_season" }),
    playerPositionAsSeason: r.many.playerPosition({ from: r.season.id, to: r.playerPosition.seasonId, alias: "playerPosition_season" }),
    playerBodyMeasurementAsSeason: r.many.playerBodyMeasurement({ from: r.season.id, to: r.playerBodyMeasurement.seasonId, alias: "playerBodyMeasurement_season" }),
    playerJerseyNumberAsSeason: r.many.playerJerseyNumber({ from: r.season.id, to: r.playerJerseyNumber.seasonId, alias: "playerJerseyNumber_season" }),
    rosterDepthChartAsSeason: r.many.rosterDepthChart({ from: r.season.id, to: r.rosterDepthChart.seasonId, alias: "rosterDepthChart_season" }),
    teamSeasonStatsAsSeason: r.many.teamSeasonStats({ from: r.season.id, to: r.teamSeasonStats.seasonId, alias: "teamSeasonStats_season" }),
    tradeAsSeason: r.many.trade({ from: r.season.id, to: r.trade.seasonId, alias: "trade_season" }),
  },
  snapCount: {
    player: r.one.player({ from: r.snapCount.playerId, to: r.player.id, alias: "snapCount_player", optional: true }),
    team: r.one.team({ from: r.snapCount.teamId, to: r.team.id, alias: "snapCount_team", optional: true }),
    game: r.one.game({ from: r.snapCount.gameId, to: r.game.id, alias: "snapCount_game", optional: true }),
    position: r.one.position({ from: r.snapCount.positionId, to: r.position.id, alias: "snapCount_position", optional: true }),
  },
  stadium: {
    gameAsStadium: r.many.game({ from: r.stadium.id, to: r.game.stadiumId, alias: "game_stadium" }),
  },
  team: {
    draftPickAsTeam: r.many.draftPick({ from: r.team.id, to: r.draftPick.teamId, alias: "draftPick_team" }),
    gameAsAwayTeam: r.many.game({ from: r.team.id, to: r.game.awayTeamId, alias: "game_awayTeam" }),
    gameAsHomeTeam: r.many.game({ from: r.team.id, to: r.game.homeTeamId, alias: "game_homeTeam" }),
    gameParticipantAsTeam: r.many.gameParticipant({ from: r.team.id, to: r.gameParticipant.teamId, alias: "gameParticipant_team" }),
    gameCoachAsTeam: r.many.gameCoach({ from: r.team.id, to: r.gameCoach.teamId, alias: "gameCoach_team" }),
    injuryReportAsTeam: r.many.injuryReport({ from: r.team.id, to: r.injuryReport.teamId, alias: "injuryReport_team" }),
    ngsPassingAsTeam: r.many.ngsPassing({ from: r.team.id, to: r.ngsPassing.teamId, alias: "ngsPassing_team" }),
    ngsReceivingAsTeam: r.many.ngsReceiving({ from: r.team.id, to: r.ngsReceiving.teamId, alias: "ngsReceiving_team" }),
    ngsRushingAsTeam: r.many.ngsRushing({ from: r.team.id, to: r.ngsRushing.teamId, alias: "ngsRushing_team" }),
    pfrAdvDefSeasonAsTeam: r.many.pfrAdvDefSeason({ from: r.team.id, to: r.pfrAdvDefSeason.teamId, alias: "pfrAdvDefSeason_team" }),
    pfrAdvPassSeasonAsTeam: r.many.pfrAdvPassSeason({ from: r.team.id, to: r.pfrAdvPassSeason.teamId, alias: "pfrAdvPassSeason_team" }),
    pfrAdvRushSeasonAsTeam: r.many.pfrAdvRushSeason({ from: r.team.id, to: r.pfrAdvRushSeason.teamId, alias: "pfrAdvRushSeason_team" }),
    pfrAdvRecSeasonAsTeam: r.many.pfrAdvRecSeason({ from: r.team.id, to: r.pfrAdvRecSeason.teamId, alias: "pfrAdvRecSeason_team" }),
    pfrAdvDefWeekAsTeam: r.many.pfrAdvDefWeek({ from: r.team.id, to: r.pfrAdvDefWeek.teamId, alias: "pfrAdvDefWeek_team" }),
    pfrAdvPassWeekAsTeam: r.many.pfrAdvPassWeek({ from: r.team.id, to: r.pfrAdvPassWeek.teamId, alias: "pfrAdvPassWeek_team" }),
    pfrAdvRecWeekAsTeam: r.many.pfrAdvRecWeek({ from: r.team.id, to: r.pfrAdvRecWeek.teamId, alias: "pfrAdvRecWeek_team" }),
    pfrAdvRushWeekAsTeam: r.many.pfrAdvRushWeek({ from: r.team.id, to: r.pfrAdvRushWeek.teamId, alias: "pfrAdvRushWeek_team" }),
    playAsPossessionTeam: r.many.play({ from: r.team.id, to: r.play.possessionTeamId, alias: "play_possessionTeam" }),
    playAsDefensiveTeam: r.many.play({ from: r.team.id, to: r.play.defensiveTeamId, alias: "play_defensiveTeam" }),
    playTeamStatsAsTeam: r.many.playTeamStats({ from: r.team.id, to: r.playTeamStats.teamId, alias: "playTeamStats_team" }),
    playPlayerAsTeam: r.many.playPlayer({ from: r.team.id, to: r.playPlayer.teamId, alias: "playPlayer_team" }),
    playTeamAsTeam: r.many.playTeam({ from: r.team.id, to: r.playTeam.teamId, alias: "playTeam_team" }),
    playerGamePassingStatsAsTeam: r.many.playerGamePassingStats({ from: r.team.id, to: r.playerGamePassingStats.teamId, alias: "playerGamePassingStats_team" }),
    playerSeasonPassingStatsAsTeam: r.many.playerSeasonPassingStats({ from: r.team.id, to: r.playerSeasonPassingStats.teamId, alias: "playerSeasonPassingStats_team" }),
    playerGameRushingStatsAsTeam: r.many.playerGameRushingStats({ from: r.team.id, to: r.playerGameRushingStats.teamId, alias: "playerGameRushingStats_team" }),
    playerSeasonRushingStatsAsTeam: r.many.playerSeasonRushingStats({ from: r.team.id, to: r.playerSeasonRushingStats.teamId, alias: "playerSeasonRushingStats_team" }),
    playerGameReceivingStatsAsTeam: r.many.playerGameReceivingStats({ from: r.team.id, to: r.playerGameReceivingStats.teamId, alias: "playerGameReceivingStats_team" }),
    playerSeasonReceivingStatsAsTeam: r.many.playerSeasonReceivingStats({ from: r.team.id, to: r.playerSeasonReceivingStats.teamId, alias: "playerSeasonReceivingStats_team" }),
    playerGameDefenseStatsAsTeam: r.many.playerGameDefenseStats({ from: r.team.id, to: r.playerGameDefenseStats.teamId, alias: "playerGameDefenseStats_team" }),
    playerSeasonDefenseStatsAsTeam: r.many.playerSeasonDefenseStats({ from: r.team.id, to: r.playerSeasonDefenseStats.teamId, alias: "playerSeasonDefenseStats_team" }),
    playerGameKickingStatsAsTeam: r.many.playerGameKickingStats({ from: r.team.id, to: r.playerGameKickingStats.teamId, alias: "playerGameKickingStats_team" }),
    playerSeasonKickingStatsAsTeam: r.many.playerSeasonKickingStats({ from: r.team.id, to: r.playerSeasonKickingStats.teamId, alias: "playerSeasonKickingStats_team" }),
    playerGamePuntingStatsAsTeam: r.many.playerGamePuntingStats({ from: r.team.id, to: r.playerGamePuntingStats.teamId, alias: "playerGamePuntingStats_team" }),
    playerSeasonPuntingStatsAsTeam: r.many.playerSeasonPuntingStats({ from: r.team.id, to: r.playerSeasonPuntingStats.teamId, alias: "playerSeasonPuntingStats_team" }),
    playerGameReturnStatsAsTeam: r.many.playerGameReturnStats({ from: r.team.id, to: r.playerGameReturnStats.teamId, alias: "playerGameReturnStats_team" }),
    playerSeasonReturnStatsAsTeam: r.many.playerSeasonReturnStats({ from: r.team.id, to: r.playerSeasonReturnStats.teamId, alias: "playerSeasonReturnStats_team" }),
    playerGameMiscStatsAsTeam: r.many.playerGameMiscStats({ from: r.team.id, to: r.playerGameMiscStats.teamId, alias: "playerGameMiscStats_team" }),
    playerSeasonMiscStatsAsTeam: r.many.playerSeasonMiscStats({ from: r.team.id, to: r.playerSeasonMiscStats.teamId, alias: "playerSeasonMiscStats_team" }),
    teamLogoAsTeam: r.many.teamLogo({ from: r.team.id, to: r.teamLogo.teamId, alias: "teamLogo_team" }),
    playerAsLatestTeam: r.many.player({ from: r.team.id, to: r.player.latestTeamId, alias: "player_latestTeam" }),
    snapCountAsTeam: r.many.snapCount({ from: r.team.id, to: r.snapCount.teamId, alias: "snapCount_team" }),
    rosterDepthChartAsTeam: r.many.rosterDepthChart({ from: r.team.id, to: r.rosterDepthChart.teamId, alias: "rosterDepthChart_team" }),
    teamGameStatsAsTeam: r.many.teamGameStats({ from: r.team.id, to: r.teamGameStats.teamId, alias: "teamGameStats_team" }),
    teamSeasonStatsAsTeam: r.many.teamSeasonStats({ from: r.team.id, to: r.teamSeasonStats.teamId, alias: "teamSeasonStats_team" }),
    tradePlayerAsFromTeam: r.many.tradePlayer({ from: r.team.id, to: r.tradePlayer.fromTeamId, alias: "tradePlayer_fromTeam" }),
    tradePlayerAsToTeam: r.many.tradePlayer({ from: r.team.id, to: r.tradePlayer.toTeamId, alias: "tradePlayer_toTeam" }),
    tradePickAsFromTeam: r.many.tradePick({ from: r.team.id, to: r.tradePick.fromTeamId, alias: "tradePick_fromTeam" }),
    tradePickAsToTeam: r.many.tradePick({ from: r.team.id, to: r.tradePick.toTeamId, alias: "tradePick_toTeam" }),
  },
  teamGameStats: {
    team: r.one.team({ from: r.teamGameStats.teamId, to: r.team.id, alias: "teamGameStats_team", optional: true }),
    game: r.one.game({ from: r.teamGameStats.gameId, to: r.game.id, alias: "teamGameStats_game", optional: true }),
  },
  teamLogo: {
    team: r.one.team({ from: r.teamLogo.teamId, to: r.team.id, alias: "teamLogo_team", optional: true }),
  },
  teamSeasonStats: {
    team: r.one.team({ from: r.teamSeasonStats.teamId, to: r.team.id, alias: "teamSeasonStats_team", optional: true }),
    season: r.one.season({ from: r.teamSeasonStats.seasonId, to: r.season.id, alias: "teamSeasonStats_season", optional: true }),
  },
  trade: {
    season: r.one.season({ from: r.trade.seasonId, to: r.season.id, alias: "trade_season", optional: true }),
    tradePlayerAsTrade: r.many.tradePlayer({ from: r.trade.id, to: r.tradePlayer.tradeId, alias: "tradePlayer_trade" }),
    tradePickAsTrade: r.many.tradePick({ from: r.trade.id, to: r.tradePick.tradeId, alias: "tradePick_trade" }),
  },
  tradePick: {
    trade: r.one.trade({ from: r.tradePick.tradeId, to: r.trade.id, alias: "tradePick_trade", optional: true }),
    fromTeam: r.one.team({ from: r.tradePick.fromTeamId, to: r.team.id, alias: "tradePick_fromTeam", optional: true }),
    toTeam: r.one.team({ from: r.tradePick.toTeamId, to: r.team.id, alias: "tradePick_toTeam", optional: true }),
  },
  tradePlayer: {
    trade: r.one.trade({ from: r.tradePlayer.tradeId, to: r.trade.id, alias: "tradePlayer_trade", optional: true }),
    fromTeam: r.one.team({ from: r.tradePlayer.fromTeamId, to: r.team.id, alias: "tradePlayer_fromTeam", optional: true }),
    toTeam: r.one.team({ from: r.tradePlayer.toTeamId, to: r.team.id, alias: "tradePlayer_toTeam", optional: true }),
    tradedPlayer: r.one.player({ from: r.tradePlayer.tradedPlayerId, to: r.player.id, alias: "tradePlayer_tradedPlayer", optional: true }),
  },
  week: {
    injuryReportAsWeek: r.many.injuryReport({ from: r.week.id, to: r.injuryReport.weekId, alias: "injuryReport_week" }),
    ngsPassingAsWeek: r.many.ngsPassing({ from: r.week.id, to: r.ngsPassing.weekId, alias: "ngsPassing_week" }),
    ngsReceivingAsWeek: r.many.ngsReceiving({ from: r.week.id, to: r.ngsReceiving.weekId, alias: "ngsReceiving_week" }),
    ngsRushingAsWeek: r.many.ngsRushing({ from: r.week.id, to: r.ngsRushing.weekId, alias: "ngsRushing_week" }),
    season: r.one.season({ from: r.week.seasonId, to: r.season.id, alias: "week_season", optional: true }),
    playerPositionAsWeek: r.many.playerPosition({ from: r.week.id, to: r.playerPosition.weekId, alias: "playerPosition_week" }),
    playerJerseyNumberAsWeek: r.many.playerJerseyNumber({ from: r.week.id, to: r.playerJerseyNumber.weekId, alias: "playerJerseyNumber_week" }),
    rosterDepthChartAsWeek: r.many.rosterDepthChart({ from: r.week.id, to: r.rosterDepthChart.weekId, alias: "rosterDepthChart_week" }),
  },
}));
