import { sqliteTable, text, integer, real, index } from "drizzle-orm/sqlite-core";
import { game } from "./games";
import { player, team } from "./reference";

export const snap_count = sqliteTable(
  "snap_count",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    gameId: integer("game_id").references(() => game.id),
    playerId: integer("player_id").references(() => player.id),
    playerName: text("player_name"),
    teamId: integer("team_id").references(() => team.id),
    opponentTeamId: integer("opponent_team_id").references(() => team.id),
    season: real("season"),
    gameType: text("game_type").notNull(),
    week: real("week"),
    position: text("position"),
    offenseSnaps: real("offense_snaps"),
    offensePct: real("offense_pct"),
    defenseSnaps: real("defense_snaps"),
    defensePct: real("defense_pct"),
    stSnaps: real("st_snaps"),
    stPct: real("st_pct"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [index("snap_game_idx").on(t.gameId), index("snap_player_idx").on(t.playerId)],
);

export const roster_weekly = sqliteTable(
  "roster_weekly",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    season: real("season"),
    position: text("position"),
    depthChartPosition: text("depth_chart_position"),
    jerseyNumber: text("jersey_number").notNull(),
    status: text("status").notNull(),
    fullName: text("full_name"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    birthDate: integer("birth_date", { mode: "timestamp_ms" }),
    height: text("height").notNull(),
    weight: text("weight").notNull(),
    college: text("college"),
    yearsExp: integer("years_exp"),
    headshotUrl: text("headshot_url"),
    ngsPosition: text("ngs_position"),
    week: integer("week"),
    gameType: text("game_type"),
    statusDescriptionAbbr: text("status_description_abbr"),
    footballName: text("football_name"),
    entryYear: integer("entry_year"),
    rookieYear: integer("rookie_year"),
    draftClub: text("draft_club"),
    draftNumber: integer("draft_number"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [
    index("rw_player_idx").on(t.playerId),
    index("rw_team_week_idx").on(t.teamId, t.season, t.week),
  ],
);

export const roster_season = sqliteTable(
  "roster_season",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    playerId: integer("player_id").references(() => player.id),
    teamId: integer("team_id").references(() => team.id),
    season: real("season"),
    position: text("position"),
    depthChartPosition: text("depth_chart_position"),
    jerseyNumber: text("jersey_number").notNull(),
    status: text("status"),
    fullName: text("full_name"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    birthDate: integer("birth_date", { mode: "timestamp_ms" }),
    height: real("height"),
    weight: integer("weight"),
    college: text("college"),
    yearsExp: integer("years_exp"),
    headshotUrl: text("headshot_url"),
    ngsPosition: text("ngs_position"),
    week: real("week"),
    gameType: text("game_type").notNull(),
    statusDescriptionAbbr: text("status_description_abbr"),
    footballName: text("football_name"),
    entryYear: integer("entry_year"),
    rookieYear: integer("rookie_year"),
    draftClub: text("draft_club"),
    draftNumber: integer("draft_number"),
    contentHash: text("content_hash"),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  },
  (t) => [index("rs_player_idx").on(t.playerId), index("rs_team_idx").on(t.teamId, t.season)],
);
