import { sqliteTable, text, integer, real, uniqueIndex } from "drizzle-orm/sqlite-core";
import { game } from "./games";
import { season, team } from "./reference";

const columns = () => ({
  completions: integer("completions"),
  attempts: integer("attempts"),
  passingYards: integer("passing_yards"),
  passingTouchdowns: integer("passing_touchdowns"),
  passingInterceptions: integer("passing_interceptions"),
  sacksSuffered: integer("sacks_suffered"),
  sackYardsLost: integer("sack_yards_lost"),
  sackFumbles: integer("sack_fumbles"),
  sackFumblesLost: integer("sack_fumbles_lost"),
  passingAirYards: integer("passing_air_yards"),
  passingYardsAfterCatch: integer("passing_yards_after_catch"),
  passingFirstDowns: integer("passing_first_downs"),
  passingExpectedPointsAdded: real("passing_expected_points_added"),
  completionPercentageOverExpected: real("completion_percentage_over_expected"),
  passingTwoPointConversions: integer("passing_two_point_conversions"),
  passes10Yards: integer("passes_10_yards"),
  passes16Yards: integer("passes_16_yards"),
  passes20Yards: integer("passes_20_yards"),
  passes40Yards: integer("passes_40_yards"),
  carries: integer("carries"),
  rushingYards: integer("rushing_yards"),
  rushingTouchdowns: integer("rushing_touchdowns"),
  rushingFumbles: integer("rushing_fumbles"),
  rushingFumblesLost: integer("rushing_fumbles_lost"),
  rushingFirstDowns: integer("rushing_first_downs"),
  rushingExpectedPointsAdded: real("rushing_expected_points_added"),
  rushingTwoPointConversions: integer("rushing_two_point_conversions"),
  rushes10Yards: integer("rushes_10_yards"),
  rushes12Yards: integer("rushes_12_yards"),
  rushes20Yards: integer("rushes_20_yards"),
  rushes40Yards: integer("rushes_40_yards"),
  receptions: integer("receptions"),
  targets: integer("targets"),
  receivingYards: integer("receiving_yards"),
  receivingTouchdowns: integer("receiving_touchdowns"),
  receivingFumbles: integer("receiving_fumbles"),
  receivingFumblesLost: integer("receiving_fumbles_lost"),
  receivingAirYards: integer("receiving_air_yards"),
  receivingYardsAfterCatch: integer("receiving_yards_after_catch"),
  receivingFirstDowns: integer("receiving_first_downs"),
  receivingExpectedPointsAdded: real("receiving_expected_points_added"),
  receivingTwoPointConversions: integer("receiving_two_point_conversions"),
  receptions10Yards: integer("receptions_10_yards"),
  receptions16Yards: integer("receptions_16_yards"),
  receptions20Yards: integer("receptions_20_yards"),
  receptions40Yards: integer("receptions_40_yards"),
  specialTeamsTouchdowns: integer("special_teams_touchdowns"),
  defensiveSoloTackles: real("defensive_solo_tackles"),
  defensiveTacklesWithAssist: real("defensive_tackles_with_assist"),
  defensiveTackleAssists: real("defensive_tackle_assists"),
  defensiveTacklesForLoss: real("defensive_tackles_for_loss"),
  defensiveTacklesForLossYards: real("defensive_tackles_for_loss_yards"),
  defensiveFumblesForced: integer("defensive_fumbles_forced"),
  defensiveSacks: real("defensive_sacks"),
  defensiveSackYards: real("defensive_sack_yards"),
  defensiveQuarterbackHits: real("defensive_quarterback_hits"),
  defensiveInterceptions: real("defensive_interceptions"),
  defensiveInterceptionYards: real("defensive_interception_yards"),
  defensivePassesDefended: real("defensive_passes_defended"),
  defensiveTouchdowns: real("defensive_touchdowns"),
  defensiveFumblesRecovered: real("defensive_fumbles_recovered"),
  defensiveSafeties: real("defensive_safeties"),
  defensivePuntsBlocked: real("defensive_punts_blocked"),
  defensivePointAfterTouchdownsBlocked: real("defensive_point_after_touchdowns_blocked"),
  defensiveFieldGoalsBlocked: real("defensive_field_goals_blocked"),
  defensiveTwoPointAttempts: real("defensive_two_point_attempts"),
  defensiveTwoPointConversions: real("defensive_two_point_conversions"),
  miscellaneousYards: real("miscellaneous_yards"),
  fumbleRecoveryOwn: real("fumble_recovery_own"),
  fumbleRecoveryYardsOwn: real("fumble_recovery_yards_own"),
  fumbleRecoveryOpponent: real("fumble_recovery_opponent"),
  fumbleRecoveryYardsOpponent: real("fumble_recovery_yards_opponent"),
  fumbleRecoveryTouchdowns: real("fumble_recovery_touchdowns"),
  penalties: real("penalties"),
  penaltyYards: real("penalty_yards"),
  timeouts: real("timeouts"),
  fumblesForcedByOpponent: real("fumbles_forced_by_opponent"),
  fumblesNotForced: real("fumbles_not_forced"),
  fumblesOutOfBounds: real("fumbles_out_of_bounds"),
  fumblesTotal: real("fumbles_total"),
  fumblesLostTotal: real("fumbles_lost_total"),
  puntReturns: real("punt_returns"),
  puntReturnYards: real("punt_return_yards"),
  kickoffReturns: real("kickoff_returns"),
  kickoffReturnYards: real("kickoff_return_yards"),
  fieldGoalsMade: real("field_goals_made"),
  fieldGoalAttempts: real("field_goal_attempts"),
  fieldGoalsMissed: real("field_goals_missed"),
  fieldGoalsBlocked: real("field_goals_blocked"),
  longestFieldGoal: real("longest_field_goal"),
  fieldGoalPercentage: real("field_goal_percentage"),
  fieldGoalsMade0to19: real("field_goals_made_0_to_19"),
  fieldGoalsMade20to29: real("field_goals_made_20_to_29"),
  fieldGoalsMade30to39: real("field_goals_made_30_to_39"),
  fieldGoalsMade40to49: real("field_goals_made_40_to_49"),
  fieldGoalsMade50to59: real("field_goals_made_50_to_59"),
  fieldGoalsMade60Plus: real("field_goals_made_60_plus"),
  fieldGoalsMissed0to19: real("field_goals_missed_0_to_19"),
  fieldGoalsMissed20to29: real("field_goals_missed_20_to_29"),
  fieldGoalsMissed30to39: real("field_goals_missed_30_to_39"),
  fieldGoalsMissed40to49: real("field_goals_missed_40_to_49"),
  fieldGoalsMissed50to59: real("field_goals_missed_50_to_59"),
  fieldGoalsMissed60Plus: real("field_goals_missed_60_plus"),
  fieldGoalsMadeDistances: text("field_goals_made_distances", { mode: "json" }).$type<number[]>(),
  fieldGoalsMissedDistances: text("field_goals_missed_distances", { mode: "json" }).$type<
    number[]
  >(),
  fieldGoalsBlockedDistances: text("field_goals_blocked_distances", { mode: "json" }).$type<
    number[]
  >(),
  fieldGoalsMadeTotalYards: real("field_goals_made_total_yards"),
  fieldGoalsMissedTotalYards: real("field_goals_missed_total_yards"),
  fieldGoalsBlockedTotalYards: real("field_goals_blocked_total_yards"),
  pointAfterTouchdownsMade: real("point_after_touchdowns_made"),
  pointAfterTouchdownAttempts: real("point_after_touchdown_attempts"),
  pointAfterTouchdownsMissed: real("point_after_touchdowns_missed"),
  pointAfterTouchdownsBlocked: real("point_after_touchdowns_blocked"),
  pointAfterTouchdownPercentage: real("point_after_touchdown_percentage"),
  gameWinningFieldGoalsMade: real("game_winning_field_goals_made"),
  gameWinningFieldGoalAttempts: real("game_winning_field_goal_attempts"),
  gameWinningFieldGoalsMissed: real("game_winning_field_goals_missed"),
  gameWinningFieldGoalsBlocked: real("game_winning_field_goals_blocked"),
  gameWinningFieldGoalDistances: text("game_winning_field_goal_distances", { mode: "json" }).$type<
    number[]
  >(),
  puntsAttempted: real("punts_attempted"),
  puntsBlocked: real("punts_blocked"),
  longestPunt: real("longest_punt"),
  puntYards: real("punt_yards"),
  puntsInside20: real("punts_inside_20"),
  puntsOutOfBounds: real("punts_out_of_bounds"),
  puntsDowned: real("punts_downed"),
  puntsTouchback: real("punts_touchback"),
  puntsFairCaught: real("punts_fair_caught"),
  puntsReturned: real("punts_returned"),
  puntReturnYardsTotal: real("punt_return_yards_total"),
  puntReturnTouchdowns: real("punt_return_touchdowns"),
  netPuntYards: real("net_punt_yards"),
});

const meta = () => ({
  contentHash: text("content_hash"),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
});

export const teamGameStats = sqliteTable(
  "team_game_stats",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    teamId: integer("team_id")
      .notNull()
      .references(() => team.id),
    gameId: integer("game_id")
      .notNull()
      .references(() => game.id),
    ...columns(),
    ...meta(),
  },
  (t) => [uniqueIndex("team_game_stats_unique_idx").on(t.teamId, t.gameId)],
);

export const teamSeasonStats = sqliteTable(
  "team_season_stats",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    teamId: integer("team_id")
      .notNull()
      .references(() => team.id),
    seasonId: integer("season_id")
      .notNull()
      .references(() => season.id),
    ...columns(),
    ...meta(),
  },
  (t) => [uniqueIndex("team_season_stats_unique_idx").on(t.teamId, t.seasonId)],
);
